"""
Final batch of cases for CLEP-v2 to reach 120+ target.
Focuses on remaining doctrines and specialized areas.
"""

FINAL_CLEP_V2_CASES = [
    # ========== REMAINING PROPERTY RIGHTS & TAKINGS ==========
    {
        "case_id": "penn_central_v_new_york_1978",
        "name": "Penn Central Transportation Co. v. City of New York",
        "citation": "438 U.S. 104 (1978)",
        "year": 1978,
        "doctrine": "property_rights",
        "summary": "Regulatory taking requires case-by-case analysis; landmark preservation law not automatic taking.",
        "holding": "Landmarks preservation law not a taking; established three-factor balancing test for regulatory takings.",
        "issue_tags": [
            "regulatory_taking",
            "landmarks_preservation",
            "balancing_test",
            "transfer_development_rights",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Fifth Amendment Takings Clause",
        "relevance_to_audit": "Foundational regulatory takings case; balances economic impact, reasonable expectations, character of action.",
    },
    {
        "case_id": "lucas_v_south_carolina_1992",
        "name": "Lucas v. South Carolina Coastal Council",
        "citation": "505 U.S. 1003 (1992)",
        "year": 1992,
        "doctrine": "property_rights",
        "summary": "Regulation denying all economically beneficial use is taking requiring compensation unless inheres in title.",
        "holding": "Regulation depriving property of all economic value is categorical taking unless justified by background principles.",
        "issue_tags": [
            "categorical_taking",
            "total_economic_loss",
            "nuisance_exception",
            "beachfront_property",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Establishes categorical taking for total economic deprivation; relevant to restrictive regulations.",
    },
    {
        "case_id": "kelo_v_city_of_new_london_2005",
        "name": "Kelo v. City of New London",
        "citation": "545 U.S. 469 (2005)",
        "year": 2005,
        "doctrine": "property_rights",
        "summary": "Economic development qualifies as public use for eminent domain; highly controversial decision.",
        "holding": "Taking private property for economic development satisfies public use requirement of Fifth Amendment.",
        "issue_tags": [
            "eminent_domain",
            "public_use",
            "economic_development",
            "private_transfer",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Broad interpretation of public use; relevant to economic development takings.",
    },
    {
        "case_id": "koontz_v_st_johns_river_2013",
        "name": "Koontz v. St. Johns River Water Management District",
        "citation": "570 U.S. 595 (2013)",
        "year": 2013,
        "doctrine": "property_rights",
        "summary": "Unconstitutional conditions doctrine applies to permit denials and monetary exactions.",
        "holding": "Government demands for property must satisfy Nollan/Dolan nexus and rough proportionality even if permit denied.",
        "issue_tags": [
            "exactions",
            "unconstitutional_conditions",
            "permit_denial",
            "monetary_demands",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Extends exactions doctrine to permit denials and money demands; limits conditional approvals.",
    },
    {
        "case_id": "nollan_v_california_1987",
        "name": "Nollan v. California Coastal Commission",
        "citation": "483 U.S. 825 (1987)",
        "year": 1987,
        "doctrine": "property_rights",
        "summary": "Permit condition must have essential nexus to legitimate state interest or violates takings clause.",
        "holding": "Coastal Commission's beach access condition lacks essential nexus to permit; unconstitutional exaction.",
        "issue_tags": [
            "exactions",
            "essential_nexus",
            "permit_conditions",
            "public_access",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Requires essential nexus for permit conditions; prevents pretextual exactions.",
    },
    {
        "case_id": "dolan_v_tigard_1994",
        "name": "Dolan v. City of Tigard",
        "citation": "512 U.S. 374 (1994)",
        "year": 1994,
        "doctrine": "property_rights",
        "summary": "Permit condition must be roughly proportional to impact; heightened scrutiny for exactions.",
        "holding": "Permit condition requiring dedication of land must be roughly proportional to development's impact.",
        "issue_tags": [
            "exactions",
            "rough_proportionality",
            "permit_conditions",
            "heightened_scrutiny",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Requires rough proportionality for permit conditions; individualizes review.",
    },
    {
        "case_id": "loretto_v_teleprompter_1982",
        "name": "Loretto v. Teleprompter Manhattan CATV Corp.",
        "citation": "458 U.S. 419 (1982)",
        "year": 1982,
        "doctrine": "property_rights",
        "summary": "Permanent physical occupation is categorical taking requiring compensation regardless of size.",
        "holding": "Permanent physical occupation, however minor, is categorical taking requiring just compensation.",
        "issue_tags": [
            "physical_taking",
            "categorical_taking",
            "permanent_occupation",
            "cable_boxes",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Establishes per se rule for permanent physical occupation; size irrelevant.",
    },
    {
        "case_id": "horne_v_usda_2015",
        "name": "Horne v. Department of Agriculture",
        "citation": "576 U.S. 350 (2015)",
        "year": 2015,
        "doctrine": "property_rights",
        "summary": "Physical appropriation of personal property is taking; no distinction between real and personal property.",
        "holding": "Government appropriation of raisins is physical taking; personal property protected like real property.",
        "issue_tags": [
            "physical_taking",
            "personal_property",
            "raisin_reserve",
            "agricultural_regulation",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Extends takings protection to personal property; physical appropriation requires compensation.",
    },
    # ========== MORE FEDERALISM & COMMERCE CLAUSE ==========
    {
        "case_id": "garcia_v_san_antonio_1985",
        "name": "Garcia v. San Antonio Metropolitan Transit Authority",
        "citation": "469 U.S. 528 (1985)",
        "year": 1985,
        "doctrine": "federal_power",
        "summary": "Federal Fair Labor Standards Act applies to state employees; political process protects states.",
        "holding": "Congress may regulate state employers under Commerce Clause; Tenth Amendment not violated.",
        "issue_tags": [
            "state_sovereignty",
            "commerce_clause",
            "flsa",
            "political_process",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Commerce Clause; Tenth Amendment",
        "relevance_to_audit": "Limits state sovereignty defense; political process primary protection.",
    },
    {
        "case_id": "national_federation_v_sebelius_2012",
        "name": "National Federation of Independent Business v. Sebelius",
        "citation": "567 U.S. 519 (2012)",
        "year": 2012,
        "doctrine": "federal_power",
        "summary": "Individual mandate constitutional as tax; Medicaid expansion coercive to states.",
        "holding": "ACA individual mandate constitutional under taxing power but not Commerce Clause; Medicaid expansion unconstitutionally coercive.",
        "issue_tags": [
            "affordable_care_act",
            "taxing_power",
            "commerce_clause",
            "coercion",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Article I; Spending Clause",
        "relevance_to_audit": "Limits Commerce Clause; defines coercion in conditional spending.",
    },
    {
        "case_id": "gonzales_v_raich_2005",
        "name": "Gonzales v. Raich",
        "citation": "545 U.S. 1 (2005)",
        "year": 2005,
        "doctrine": "federal_power",
        "summary": "Congress may regulate intrastate marijuana cultivation under Commerce Clause using aggregation principle.",
        "holding": "Federal marijuana prohibition constitutional as applied to intrastate cultivation and possession for medical use.",
        "issue_tags": [
            "commerce_clause",
            "aggregation",
            "controlled_substances",
            "medical_marijuana",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Commerce Clause",
        "relevance_to_audit": "Broad commerce power for comprehensive regulation; aggregation principle applies.",
    },
    {
        "case_id": "us_v_morrison_2000",
        "name": "United States v. Morrison",
        "citation": "529 U.S. 598 (2000)",
        "year": 2000,
        "doctrine": "federal_power",
        "summary": "Violence Against Women Act civil remedy exceeds Commerce Clause authority; gender-motivated violence not economic activity.",
        "holding": "VAWA civil remedy unconstitutional; Congress cannot regulate non-economic violent crime under Commerce Clause.",
        "issue_tags": [
            "commerce_clause_limits",
            "non_economic_activity",
            "gender_violence",
            "federalism",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Commerce Clause",
        "relevance_to_audit": "Limits federal commerce power; non-economic local crime beyond congressional reach.",
    },
    # ========== MORE EQUAL PROTECTION & CIVIL RIGHTS ==========
    {
        "case_id": "korematsu_v_united_states_1944",
        "name": "Korematsu v. United States",
        "citation": "323 U.S. 214 (1944)",
        "year": 1944,
        "doctrine": "equal_protection",
        "summary": "Japanese internment upheld under strict scrutiny; widely criticized and effectively overruled.",
        "holding": "Exclusion of Japanese Americans from West Coast during WWII constitutional (DISCREDITED).",
        "issue_tags": [
            "japanese_internment",
            "strict_scrutiny",
            "racial_classification",
            "war_powers",
        ],
        "doctrinal_weight": 0.0,
        "constitutional_basis": "Due Process; Equal Protection",
        "relevance_to_audit": "Historically discredited; example of improper deference to executive in wartime.",
    },
    {
        "case_id": "hirabayashi_v_united_states_1943",
        "name": "Hirabayashi v. United States",
        "citation": "320 U.S. 81 (1943)",
        "year": 1943,
        "doctrine": "equal_protection",
        "summary": "Curfew targeting Japanese Americans upheld as wartime necessity; later discredited.",
        "holding": "Wartime curfew based on Japanese ancestry constitutional (DISCREDITED).",
        "issue_tags": [
            "japanese_american_curfew",
            "war_powers",
            "racial_classification",
            "discredited",
        ],
        "doctrinal_weight": 0.0,
        "constitutional_basis": "War Powers",
        "relevance_to_audit": "Historical case showing danger of wartime racial discrimination; now discredited.",
    },
    {
        "case_id": "plyler_v_doe_1982",
        "name": "Plyler v. Doe",
        "citation": "457 U.S. 202 (1982)",
        "year": 1982,
        "doctrine": "equal_protection",
        "summary": "States cannot deny free public education to undocumented children; fails rational basis review.",
        "holding": "Texas law denying free public education to undocumented children violates Equal Protection Clause.",
        "issue_tags": [
            "education_access",
            "undocumented_children",
            "heightened_rational_basis",
            "fundamental_right",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Protects children from consequences of parents' status; education critically important.",
    },
    {
        "case_id": "frontiero_v_richardson_1973",
        "name": "Frontiero v. Richardson",
        "citation": "411 U.S. 677 (1973)",
        "year": 1973,
        "doctrine": "equal_protection",
        "summary": "Gender-based classification in military benefits violates equal protection; plurality applies strict scrutiny.",
        "holding": "Military policy providing automatic benefits for male spouses but requiring proof of dependency for female spouses unconstitutional.",
        "issue_tags": [
            "gender_discrimination",
            "military_benefits",
            "suspect_classification",
            "strict_scrutiny",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fifth Amendment Due Process",
        "relevance_to_audit": "Gender classifications subject to heightened scrutiny; automatic benefit denial impermissible.",
    },
    {
        "case_id": "craig_v_boren_1976",
        "name": "Craig v. Boren",
        "citation": "429 U.S. 190 (1976)",
        "year": 1976,
        "doctrine": "equal_protection",
        "summary": "Gender classifications subject to intermediate scrutiny; must serve important objectives and be substantially related.",
        "holding": "Oklahoma law setting different drinking ages for men and women violates Equal Protection; fails intermediate scrutiny.",
        "issue_tags": [
            "gender_discrimination",
            "intermediate_scrutiny",
            "drinking_age",
            "statistical_evidence",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Establishes intermediate scrutiny for gender classifications; important and substantial relationship required.",
    },
    {
        "case_id": "united_states_v_virginia_1996",
        "name": "United States v. Virginia",
        "citation": "518 U.S. 515 (1996)",
        "year": 1996,
        "doctrine": "equal_protection",
        "summary": "VMI's male-only admissions policy violates Equal Protection; exceedingly persuasive justification required for gender classification.",
        "holding": "Virginia Military Institute's exclusion of women violates Equal Protection Clause.",
        "issue_tags": [
            "gender_discrimination",
            "single_sex_education",
            "exceedingly_persuasive_justification",
            "intermediate_scrutiny",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Heightens intermediate scrutiny standard for gender; skeptical of separate but equal.",
    },
    # ========== ADDITIONAL SPECIALIZED CASES ==========
    {
        "case_id": "arizona_v_united_states_2012",
        "name": "Arizona v. United States",
        "citation": "567 U.S. 387 (2012)",
        "year": 2012,
        "doctrine": "separation_of_powers",
        "summary": "Federal immigration law preempts major portions of Arizona SB 1070; immigration enforcement is federal.",
        "holding": "Three provisions of Arizona SB 1070 preempted by federal immigration law; one provision upheld.",
        "issue_tags": ["preemption", "immigration", "state_enforcement", "federalism"],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Supremacy Clause; Article I",
        "relevance_to_audit": "Federal immigration enforcement preempts state regulation; limits state immigration laws.",
    },
    {
        "case_id": "bush_v_gore_2000",
        "name": "Bush v. Gore",
        "citation": "531 U.S. 98 (2000)",
        "year": 2000,
        "doctrine": "equal_protection",
        "summary": "Florida recount lacking uniform standards violates Equal Protection; case limited to its facts.",
        "holding": "Florida Supreme Court recount order lacking uniform standards violates Equal Protection; time insufficient for constitutional recount.",
        "issue_tags": [
            "election_law",
            "equal_protection",
            "voting_standards",
            "presidential_election",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Requires uniform standards in vote counting; equal treatment of voters.",
    },
    {
        "case_id": "bush_v_vera_1996",
        "name": "Bush v. Vera",
        "citation": "517 U.S. 952 (1996)",
        "year": 1996,
        "doctrine": "equal_protection",
        "summary": "Bizarrely shaped districts with race as predominant factor violate Equal Protection.",
        "holding": "Texas redistricting plan using race as predominant factor in drawing district lines violates Equal Protection.",
        "issue_tags": [
            "redistricting",
            "racial_gerrymandering",
            "strict_scrutiny",
            "bizarre_shape",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Limits racial gerrymandering; race cannot be predominant factor absent compelling interest.",
    },
    {
        "case_id": "shaw_v_reno_1993",
        "name": "Shaw v. Reno",
        "citation": "509 U.S. 630 (1993)",
        "year": 1993,
        "doctrine": "equal_protection",
        "summary": "Bizarrely shaped majority-minority districts subject to strict scrutiny under Equal Protection.",
        "holding": "Redistricting plan so irregular that it can be understood only as segregating voters by race states Equal Protection claim.",
        "issue_tags": [
            "racial_gerrymandering",
            "redistricting",
            "strict_scrutiny",
            "majority_minority_district",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Race-based redistricting subject to strict scrutiny; bizarre shapes trigger review.",
    },
    {
        "case_id": "rucho_v_common_cause_2019",
        "name": "Rucho v. Common Cause",
        "citation": "139 S. Ct. 2484 (2019)",
        "year": 2019,
        "doctrine": "constitutional_structure",
        "summary": "Partisan gerrymandering claims are non-justiciable political questions.",
        "holding": "Federal courts lack authority to adjudicate partisan gerrymandering claims; political question.",
        "issue_tags": [
            "partisan_gerrymandering",
            "political_question",
            "redistricting",
            "justiciability",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Article III; Political Question Doctrine",
        "relevance_to_audit": "Removes federal judicial review of partisan gerrymandering; state courts remain available.",
    },
    {
        "case_id": "shelley_v_kraemer_1948",
        "name": "Shelley v. Kraemer",
        "citation": "334 U.S. 1 (1948)",
        "year": 1948,
        "doctrine": "equal_protection",
        "summary": "Judicial enforcement of racially restrictive covenants constitutes state action violating Equal Protection.",
        "holding": "State court enforcement of private racially restrictive covenant violates Fourteenth Amendment.",
        "issue_tags": [
            "state_action",
            "restrictive_covenant",
            "racial_discrimination",
            "judicial_enforcement",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Defines state action; judicial enforcement of private discrimination is state action.",
    },
    {
        "case_id": "miller_v_alabama_2012",
        "name": "Miller v. Alabama",
        "citation": "567 U.S. 460 (2012)",
        "year": 2012,
        "doctrine": "eighth_amendment",
        "summary": "Mandatory life without parole for juveniles violates Eighth Amendment; individualized sentencing required.",
        "holding": "Mandatory life without parole sentences for juvenile offenders violate Eighth Amendment.",
        "issue_tags": [
            "juvenile_sentencing",
            "life_without_parole",
            "cruel_unusual_punishment",
            "individualized_sentencing",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Eighth Amendment",
        "relevance_to_audit": "Protects juveniles from mandatory LWOP; requires individualized consideration.",
    },
    {
        "case_id": "roper_v_simmons_2005",
        "name": "Roper v. Simmons",
        "citation": "543 U.S. 551 (2005)",
        "year": 2005,
        "doctrine": "eighth_amendment",
        "summary": "Death penalty for crimes committed by juveniles violates Eighth Amendment.",
        "holding": "Eighth and Fourteenth Amendments forbid execution of offenders who were under 18 when crimes committed.",
        "issue_tags": [
            "juvenile_death_penalty",
            "cruel_unusual_punishment",
            "evolving_standards",
            "proportionality",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Eighth Amendment",
        "relevance_to_audit": "Categorically bars juvenile death penalty; evolving standards of decency.",
    },
    {
        "case_id": "atkins_v_virginia_2002",
        "name": "Atkins v. Virginia",
        "citation": "536 U.S. 304 (2002)",
        "year": 2002,
        "doctrine": "eighth_amendment",
        "summary": "Executing intellectually disabled violates Eighth Amendment; national consensus against practice.",
        "holding": "Execution of intellectually disabled persons is cruel and unusual punishment prohibited by Eighth Amendment.",
        "issue_tags": [
            "intellectual_disability",
            "death_penalty",
            "cruel_unusual_punishment",
            "categorical_bar",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Eighth Amendment",
        "relevance_to_audit": "Categorically bars execution of intellectually disabled; evolving standards.",
    },
]

if __name__ == "__main__":
    print(f"Final CLEP-v2 cases: {len(FINAL_CLEP_V2_CASES)}")
