"""
Additional cases for CLEP-v2 to reach 120-200 case target.
Covers remaining areas and expands key doctrines.
"""

ADDITIONAL_CLEP_V2_CASES = [
    # ========== MORE FIRST AMENDMENT CASES ==========
    {
        "case_id": "tinker_v_des_moines_1969",
        "name": "Tinker v. Des Moines Independent Community School District",
        "citation": "393 U.S. 503 (1969)",
        "year": 1969,
        "doctrine": "first_amendment",
        "summary": "Students retain First Amendment rights in school; symbolic speech protected unless materially disrupts.",
        "holding": "Students do not shed constitutional rights at schoolhouse gate; armband protest protected absent material disruption.",
        "issue_tags": [
            "student_speech",
            "symbolic_speech",
            "school_regulation",
            "substantial_disruption",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Protects student speech rights; relevant to school disciplinary policies.",
    },
    {
        "case_id": "brandenburg_v_ohio_1969",
        "name": "Brandenburg v. Ohio",
        "citation": "395 U.S. 444 (1969)",
        "year": 1969,
        "doctrine": "first_amendment",
        "summary": "Government cannot punish inflammatory speech unless directed to inciting imminent lawless action and likely to do so.",
        "holding": "Abstract advocacy of violence protected; only incitement to imminent lawless action punishable.",
        "issue_tags": [
            "incitement",
            "imminent_lawless_action",
            "advocacy",
            "free_speech",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Highest protection for speech; limits government suppression of controversial expression.",
    },
    {
        "case_id": "virginia_v_black_2003",
        "name": "Virginia v. Black",
        "citation": "538 U.S. 343 (2003)",
        "year": 2003,
        "doctrine": "first_amendment",
        "summary": "State may ban cross burning with intent to intimidate; true threats not protected by First Amendment.",
        "holding": "Ban on cross burning constitutional if statute requires intent to intimidate; true threats exception to First Amendment.",
        "issue_tags": [
            "true_threats",
            "intimidation",
            "symbolic_speech",
            "hate_speech",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Defines true threats exception; relevant to evaluating threatening communications.",
    },
    {
        "case_id": "citizens_united_v_fec_2010",
        "name": "Citizens United v. Federal Election Commission",
        "citation": "558 U.S. 310 (2010)",
        "year": 2010,
        "doctrine": "first_amendment",
        "summary": "Corporations have First Amendment right to make independent political expenditures; no corruption from independent spending.",
        "holding": "Government may not restrict independent expenditures by corporations, unions, or associations for political speech.",
        "issue_tags": [
            "corporate_speech",
            "campaign_finance",
            "independent_expenditures",
            "political_speech",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Protects corporate political speech; relevant to campaign finance and vendor influence.",
    },
    {
        "case_id": "new_york_times_v_sullivan_1964",
        "name": "New York Times Co. v. Sullivan",
        "citation": "376 U.S. 254 (1964)",
        "year": 1964,
        "doctrine": "first_amendment",
        "summary": "Public officials must prove actual malice to recover libel damages for statements about official conduct.",
        "holding": "First Amendment requires public official to prove actual malice (knowledge of falsity or reckless disregard) in defamation suit.",
        "issue_tags": [
            "defamation",
            "actual_malice",
            "public_official",
            "freedom_of_press",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Protects robust public debate; high bar for official defamation claims.",
    },
    {
        "case_id": "texas_v_johnson_1989",
        "name": "Texas v. Johnson",
        "citation": "491 U.S. 397 (1989)",
        "year": 1989,
        "doctrine": "first_amendment",
        "summary": "Flag burning is expressive conduct protected by First Amendment.",
        "holding": "Government may not prohibit expression of idea merely because society finds it offensive; flag burning protected.",
        "issue_tags": [
            "symbolic_speech",
            "flag_desecration",
            "expressive_conduct",
            "content_neutrality",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Protects offensive symbolic speech; government cannot suppress based on disagreement with message.",
    },
    {
        "case_id": "snyder_v_phelps_2011",
        "name": "Snyder v. Phelps",
        "citation": "562 U.S. 443 (2011)",
        "year": 2011,
        "doctrine": "first_amendment",
        "summary": "Speech on matters of public concern at public place receives heightened First Amendment protection even if offensive.",
        "holding": "Westboro Baptist Church protest at military funeral protected by First Amendment despite hurtful content.",
        "issue_tags": [
            "public_concern",
            "offensive_speech",
            "funeral_protest",
            "heightened_protection",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Protects speech on public issues even if deeply offensive to private individuals.",
    },
    {
        "case_id": "employment_division_v_smith_1990",
        "name": "Employment Division v. Smith",
        "citation": "494 U.S. 872 (1990)",
        "year": 1990,
        "doctrine": "first_amendment",
        "summary": "Neutral law of general applicability need not accommodate religious practice; no religious exemption required.",
        "holding": "Free Exercise Clause does not require religious exemption from neutral, generally applicable laws.",
        "issue_tags": [
            "free_exercise",
            "religious_exemption",
            "neutral_laws",
            "peyote",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "First Amendment Free Exercise Clause",
        "relevance_to_audit": "Limits religious exemptions; relevant to evaluating accommodation requests.",
    },
    {
        "case_id": "church_of_lukumi_v_hialeah_1993",
        "name": "Church of the Lukumi Babalu Aye, Inc. v. City of Hialeah",
        "citation": "508 U.S. 520 (1993)",
        "year": 1993,
        "doctrine": "first_amendment",
        "summary": "Laws targeting specific religious practices violate Free Exercise Clause; must be neutral and generally applicable.",
        "holding": "City ordinances prohibiting animal sacrifice for religious purposes unconstitutional; not neutral toward religion.",
        "issue_tags": [
            "free_exercise",
            "religious_targeting",
            "animal_sacrifice",
            "neutrality",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Prevents religious discrimination; laws must be genuinely neutral and generally applicable.",
    },
    # ========== MORE FOURTH AMENDMENT CASES ==========
    {
        "case_id": "kyllo_v_united_states_2001",
        "name": "Kyllo v. United States",
        "citation": "533 U.S. 27 (2001)",
        "year": 2001,
        "doctrine": "fourth_amendment",
        "summary": "Thermal imaging of home to detect heat signature is Fourth Amendment search requiring warrant.",
        "holding": "Use of sense-enhancing technology to obtain information about home interior is search requiring warrant.",
        "issue_tags": [
            "thermal_imaging",
            "sense_enhancing_technology",
            "home_privacy",
            "warrant_requirement",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Protects home from technological surveillance; relevant to emerging surveillance technologies.",
    },
    {
        "case_id": "florida_v_riley_1989",
        "name": "Florida v. Riley",
        "citation": "488 U.S. 445 (1989)",
        "year": 1989,
        "doctrine": "fourth_amendment",
        "summary": "Aerial surveillance from helicopter at 400 feet not a search; no reasonable expectation of privacy.",
        "holding": "Observation of greenhouse interior from helicopter in public airspace not a Fourth Amendment search.",
        "issue_tags": [
            "aerial_surveillance",
            "open_fields",
            "privacy_expectation",
            "curtilage",
        ],
        "doctrinal_weight": 0.80,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Limits privacy in areas visible from public airspace; relevant to drone surveillance.",
    },
    {
        "case_id": "california_v_ciraolo_1986",
        "name": "California v. Ciraolo",
        "citation": "476 U.S. 207 (1986)",
        "year": 1986,
        "doctrine": "fourth_amendment",
        "summary": "Aerial observation from fixed-wing aircraft at 1,000 feet not a search.",
        "holding": "Naked-eye observation of fenced backyard from public airspace not a Fourth Amendment search.",
        "issue_tags": [
            "aerial_surveillance",
            "open_fields",
            "curtilage",
            "privacy_expectation",
        ],
        "doctrinal_weight": 0.78,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Establishes aerial surveillance baseline; relevant to drone and aircraft surveillance programs.",
    },
    {
        "case_id": "maryland_v_king_2013",
        "name": "Maryland v. King",
        "citation": "569 U.S. 435 (2013)",
        "year": 2013,
        "doctrine": "fourth_amendment",
        "summary": "DNA swab of arrestee for serious offense is reasonable search; aids in identification.",
        "holding": "Taking and analyzing DNA cheek swab from arrestees constitutional; legitimate government interest in identification.",
        "issue_tags": [
            "dna_collection",
            "arrestee_search",
            "identification",
            "biometric_data",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Permits biometric collection from arrestees; relevant to DNA database programs.",
    },
    {
        "case_id": "safford_v_redding_2009",
        "name": "Safford Unified School District v. Redding",
        "citation": "557 U.S. 364 (2009)",
        "year": 2009,
        "doctrine": "fourth_amendment",
        "summary": "Strip search of student for prescription-strength ibuprofen violated Fourth Amendment; intrusion unjustified.",
        "holding": "Strip search of 13-year-old student not justified by suspicion she possessed ibuprofen; violated Fourth Amendment.",
        "issue_tags": [
            "student_search",
            "strip_search",
            "reasonable_suspicion",
            "school_context",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Limits invasiveness of student searches; scope must match nature of infraction.",
    },
    {
        "case_id": "new_jersey_v_tlo_1985",
        "name": "New Jersey v. T.L.O.",
        "citation": "469 U.S. 325 (1985)",
        "year": 1985,
        "doctrine": "fourth_amendment",
        "summary": "School officials need only reasonable suspicion (not probable cause) to search students.",
        "holding": "Fourth Amendment applies to school searches but reasonable suspicion standard applies, not probable cause.",
        "issue_tags": [
            "student_search",
            "reasonable_suspicion",
            "school_authority",
            "lowered_standard",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Establishes lower threshold for school searches; balances student rights with school safety.",
    },
    {
        "case_id": "board_of_education_v_earls_2002",
        "name": "Board of Education v. Earls",
        "citation": "536 U.S. 822 (2002)",
        "year": 2002,
        "doctrine": "fourth_amendment",
        "summary": "Suspicionless drug testing of students participating in competitive extracurricular activities is reasonable.",
        "holding": "School policy requiring drug tests for students in extracurricular activities constitutional under special needs doctrine.",
        "issue_tags": [
            "drug_testing",
            "special_needs",
            "extracurricular_activities",
            "suspicionless_search",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Permits suspicionless searches in school context; expands special needs exception.",
    },
    {
        "case_id": "vernonia_v_acton_1995",
        "name": "Vernonia School District 47J v. Acton",
        "citation": "515 U.S. 646 (1995)",
        "year": 1995,
        "doctrine": "fourth_amendment",
        "summary": "Suspicionless drug testing of student athletes is reasonable under Fourth Amendment.",
        "holding": "Random drug testing of student athletes constitutional; students have reduced privacy expectation in school.",
        "issue_tags": [
            "drug_testing",
            "student_athletes",
            "special_needs",
            "reduced_privacy",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Establishes special needs exception for student athletes; reduced privacy expectation.",
    },
    {
        "case_id": "city_of_indianapolis_v_edmond_2000",
        "name": "City of Indianapolis v. Edmond",
        "citation": "531 U.S. 32 (2000)",
        "year": 2000,
        "doctrine": "fourth_amendment",
        "summary": "Suspicionless vehicle checkpoints for general crime detection violate Fourth Amendment.",
        "holding": "Drug interdiction checkpoints violate Fourth Amendment; primary purpose cannot be general crime detection.",
        "issue_tags": [
            "checkpoint",
            "suspicionless_search",
            "primary_purpose",
            "crime_detection",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Limits checkpoint authority; primary purpose must be legitimate special need, not general law enforcement.",
    },
    {
        "case_id": "illinois_v_caballes_2005",
        "name": "Illinois v. Caballes",
        "citation": "543 U.S. 405 (2005)",
        "year": 2005,
        "doctrine": "fourth_amendment",
        "summary": "Dog sniff during lawful traffic stop not a search; no reasonable expectation of privacy in contraband.",
        "holding": "Dog sniff of vehicle during lawful traffic stop not a Fourth Amendment search if not prolonging stop.",
        "issue_tags": [
            "dog_sniff",
            "traffic_stop",
            "privacy_expectation",
            "contraband",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Permits dog sniff during lawful stop without suspicion; limited to duration of lawful stop.",
    },
    {
        "case_id": "florence_v_board_2012",
        "name": "Florence v. Board of Chosen Freeholders",
        "citation": "566 U.S. 318 (2012)",
        "year": 2012,
        "doctrine": "fourth_amendment",
        "summary": "Strip search of arrestee being admitted to general jail population reasonable even for minor offense.",
        "holding": "Strip search procedures for detainees entering general jail population constitutional regardless of offense.",
        "issue_tags": [
            "strip_search",
            "jail_intake",
            "institutional_security",
            "minor_offense",
        ],
        "doctrinal_weight": 0.83,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Defers to jail security needs; permits intrusive searches for institutional safety.",
    },
    # ========== MORE DUE PROCESS CASES ==========
    {
        "case_id": "hamdi_v_rumsfeld_2004",
        "name": "Hamdi v. Rumsfeld",
        "citation": "542 U.S. 507 (2004)",
        "year": 2004,
        "doctrine": "due_process",
        "summary": "U.S. citizen designated enemy combatant entitled to due process to challenge detention.",
        "holding": "Citizen-detainees challenging enemy combatant status entitled to notice of factual basis and meaningful opportunity to rebut.",
        "issue_tags": [
            "enemy_combatant",
            "habeas_corpus",
            "due_process",
            "war_on_terror",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Fifth Amendment Due Process",
        "relevance_to_audit": "Protects due process even in national security context; requires meaningful hearing.",
    },
    {
        "case_id": "boumediene_v_bush_2008",
        "name": "Boumediene v. Bush",
        "citation": "553 U.S. 723 (2008)",
        "year": 2008,
        "doctrine": "due_process",
        "summary": "Guantanamo detainees have constitutional right to habeas corpus; MCA inadequate substitute.",
        "holding": "Detainees at Guantanamo Bay have constitutional privilege of habeas corpus; MCA unconstitutional suspension.",
        "issue_tags": [
            "habeas_corpus",
            "guantanamo",
            "enemy_combatant",
            "suspension_clause",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Suspension Clause; Due Process",
        "relevance_to_audit": "Extends habeas rights to Guantanamo; limits executive detention authority.",
    },
    {
        "case_id": "rochin_v_california_1952",
        "name": "Rochin v. California",
        "citation": "342 U.S. 165 (1952)",
        "year": 1952,
        "doctrine": "due_process",
        "summary": "Forced stomach pumping to retrieve evidence shocks the conscience and violates due process.",
        "holding": "Police conduct that shocks the conscience violates Fourteenth Amendment Due Process.",
        "issue_tags": [
            "substantive_due_process",
            "police_misconduct",
            "shocks_conscience",
            "bodily_integrity",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Establishes shocks-the-conscience test for substantive due process violations.",
    },
    {
        "case_id": "county_of_sacramento_v_lewis_1998",
        "name": "County of Sacramento v. Lewis",
        "citation": "523 U.S. 833 (1998)",
        "year": 1998,
        "doctrine": "due_process",
        "summary": "High-speed police chase causing death violates substantive due process only if shocks conscience.",
        "holding": "Substantive due process violated only by executive action intended to injure or that shocks conscience.",
        "issue_tags": [
            "police_chase",
            "substantive_due_process",
            "shocks_conscience",
            "deliberate_indifference",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "High bar for substantive due process in high-speed pursuits; requires intent or deliberate indifference.",
    },
    {
        "case_id": "deshaney_v_winnebago_1989",
        "name": "DeShaney v. Winnebago County Department of Social Services",
        "citation": "489 U.S. 189 (1989)",
        "year": 1989,
        "doctrine": "due_process",
        "summary": "Due Process Clause generally does not impose affirmative duty on state to protect individuals from private violence.",
        "holding": "State's failure to protect individual from private violence not due process violation absent special relationship.",
        "issue_tags": [
            "state_duty",
            "affirmative_obligation",
            "child_abuse",
            "special_relationship",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Limits state liability; no general duty to protect absent custody or special relationship.",
    },
    {
        "case_id": "town_of_castle_rock_v_gonzales_2005",
        "name": "Town of Castle Rock v. Gonzales",
        "citation": "545 U.S. 748 (2005)",
        "year": 2005,
        "doctrine": "due_process",
        "summary": "No property interest in police enforcement of restraining order; no due process violation from non-enforcement.",
        "holding": "Restraining order does not create property interest in police enforcement; discretionary enforcement permissible.",
        "issue_tags": [
            "police_discretion",
            "restraining_order",
            "property_interest",
            "enforcement",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Limits due process claims for non-enforcement; police retain enforcement discretion.",
    },
    {
        "case_id": "sandin_v_conner_1995",
        "name": "Sandin v. Conner",
        "citation": "515 U.S. 472 (1995)",
        "year": 1995,
        "doctrine": "due_process",
        "summary": "Prisoner disciplinary segregation for 30 days does not trigger due process protections absent atypical hardship.",
        "holding": "Liberty interest in avoiding confinement conditions exists only if conditions impose atypical and significant hardship.",
        "issue_tags": [
            "prisoner_rights",
            "disciplinary_segregation",
            "liberty_interest",
            "atypical_hardship",
        ],
        "doctrinal_weight": 0.80,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Limits due process protections for prisoners; only atypical hardships trigger hearings.",
    },
    # ========== MORE EQUAL PROTECTION CASES ==========
    {
        "case_id": "city_of_cleburne_v_cleburne_1985",
        "name": "City of Cleburne v. Cleburne Living Center",
        "citation": "473 U.S. 432 (1985)",
        "year": 1985,
        "doctrine": "equal_protection",
        "summary": "Intellectual disability not quasi-suspect class; but permit denial for group home based on animus violates equal protection.",
        "holding": "Requiring special permit for group home for intellectually disabled violates equal protection when based on irrational prejudice.",
        "issue_tags": ["rational_basis", "animus", "intellectual_disability", "zoning"],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Rational basis with bite; government action based on animus violates equal protection.",
    },
    {
        "case_id": "romer_v_evans_1996",
        "name": "Romer v. Evans",
        "citation": "517 U.S. 620 (1996)",
        "year": 1996,
        "doctrine": "equal_protection",
        "summary": "State constitutional amendment barring anti-discrimination protection for gays and lesbians violates equal protection.",
        "holding": "Colorado Amendment 2 imposing broad disability on gays and lesbians fails rational basis review; based on animus.",
        "issue_tags": [
            "sexual_orientation",
            "rational_basis",
            "animus",
            "anti_discrimination",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Applies rational basis review to strike down discrimination based on animus.",
    },
    {
        "case_id": "united_states_v_windsor_2013",
        "name": "United States v. Windsor",
        "citation": "570 U.S. 744 (2013)",
        "year": 2013,
        "doctrine": "equal_protection",
        "summary": "Defense of Marriage Act (DOMA) Section 3 unconstitutional; federal government must recognize state-sanctioned same-sex marriages.",
        "holding": "DOMA's refusal to recognize state same-sex marriages violates Fifth Amendment Due Process and equal protection principles.",
        "issue_tags": ["same_sex_marriage", "doma", "federalism", "equal_protection"],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Fifth Amendment Due Process",
        "relevance_to_audit": "Invalidates discriminatory federal non-recognition of state marriages; equal dignity principle.",
    },
    {
        "case_id": "bolling_v_sharpe_1954",
        "name": "Bolling v. Sharpe",
        "citation": "347 U.S. 497 (1954)",
        "year": 1954,
        "doctrine": "due_process",
        "summary": "Fifth Amendment Due Process incorporates equal protection principles; racial segregation in DC schools unconstitutional.",
        "holding": "Racial segregation in District of Columbia public schools violates Fifth Amendment Due Process (companion to Brown).",
        "issue_tags": [
            "reverse_incorporation",
            "racial_segregation",
            "equal_protection",
            "due_process",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Applies equal protection to federal government through Fifth Amendment due process.",
    },
    {
        "case_id": "regents_v_bakke_1978",
        "name": "Regents of the University of California v. Bakke",
        "citation": "438 U.S. 265 (1978)",
        "year": 1978,
        "doctrine": "equal_protection",
        "summary": "Racial quotas in university admissions unconstitutional; race may be considered as one factor among many.",
        "holding": "Rigid racial quota system violates Equal Protection; race-conscious admissions permissible as one factor.",
        "issue_tags": [
            "affirmative_action",
            "racial_quotas",
            "strict_scrutiny",
            "diversity",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Applies strict scrutiny to racial classifications; permits diversity consideration without quotas.",
    },
    {
        "case_id": "fisher_v_texas_2016",
        "name": "Fisher v. University of Texas (Fisher II)",
        "citation": "579 U.S. 365 (2016)",
        "year": 2016,
        "doctrine": "equal_protection",
        "summary": "Race-conscious university admissions constitutional if narrowly tailored to achieve diversity and no workable alternative exists.",
        "holding": "University of Texas's race-conscious admissions policy constitutional; satisfies strict scrutiny.",
        "issue_tags": [
            "affirmative_action",
            "strict_scrutiny",
            "narrow_tailoring",
            "diversity",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Upholds limited race-conscious admissions under strict scrutiny analysis.",
    },
    {
        "case_id": "students_for_fair_admissions_v_harvard_2023",
        "name": "Students for Fair Admissions, Inc. v. President & Fellows of Harvard College",
        "citation": "143 S. Ct. 2141 (2023)",
        "year": 2023,
        "doctrine": "equal_protection",
        "summary": "Race-conscious university admissions programs violate Equal Protection; overrules Bakke/Grutter framework.",
        "holding": "Harvard and UNC race-conscious admissions programs unconstitutional; cannot use race as factor in admissions.",
        "issue_tags": [
            "affirmative_action",
            "strict_scrutiny",
            "overrule",
            "colorblind",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Major shift: prohibits use of race in admissions; mandates colorblind approach.",
    },
    {
        "case_id": "grutter_v_bollinger_2003",
        "name": "Grutter v. Bollinger",
        "citation": "539 U.S. 306 (2003)",
        "year": 2003,
        "doctrine": "equal_protection",
        "summary": "Student body diversity is compelling interest; individualized race-conscious admissions constitutional (effectively overruled 2023).",
        "holding": "Law school's narrowly tailored use of race in admissions constitutional; diversity compelling interest (overruled by SFFA).",
        "issue_tags": [
            "affirmative_action",
            "compelling_interest",
            "narrow_tailoring",
            "overruled",
        ],
        "doctrinal_weight": 0.0,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Historical precedent overruled by Students for Fair Admissions (2023).",
    },
    # ========== MORE SEPARATION OF POWERS CASES ==========
    {
        "case_id": "youngstown_v_sawyer_1952",
        "name": "Youngstown Sheet & Tube Co. v. Sawyer",
        "citation": "343 U.S. 579 (1952)",
        "year": 1952,
        "doctrine": "separation_of_powers",
        "summary": "President lacks inherent authority to seize private property absent congressional authorization.",
        "holding": "President's seizure of steel mills unconstitutional; executive power does not include lawmaking authority.",
        "issue_tags": [
            "executive_power",
            "seizure",
            "inherent_authority",
            "separation_of_powers",
        ],
        "doctrinal_weight": 0.98,
        "constitutional_basis": "Article II; Separation of Powers",
        "relevance_to_audit": "Foundational separation of powers case; limits executive action without statutory authority.",
    },
    {
        "case_id": "ins_v_chadha_1983",
        "name": "INS v. Chadha",
        "citation": "462 U.S. 919 (1983)",
        "year": 1983,
        "doctrine": "separation_of_powers",
        "summary": "Legislative veto violates separation of powers; Congress must use bicameralism and presentment.",
        "holding": "One-house legislative veto unconstitutional; violates Presentment Clause and bicameralism requirements.",
        "issue_tags": [
            "legislative_veto",
            "presentment",
            "bicameralism",
            "separation_of_powers",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Article I; Presentment Clause",
        "relevance_to_audit": "Invalidates legislative vetoes; Congress must follow constitutional lawmaking process.",
    },
    {
        "case_id": "clinton_v_new_york_1998",
        "name": "Clinton v. City of New York",
        "citation": "524 U.S. 417 (1998)",
        "year": 1998,
        "doctrine": "separation_of_powers",
        "summary": "Line-item veto violates Presentment Clause; President cannot unilaterally amend or repeal statutes.",
        "holding": "Line Item Veto Act unconstitutional; permits President to cancel parts of bills after signing into law.",
        "issue_tags": [
            "line_item_veto",
            "presentment_clause",
            "statutory_amendment",
            "executive_power",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Article I; Presentment Clause",
        "relevance_to_audit": "Limits executive power to modify legislation; constitutional amendment process required.",
    },
    {
        "case_id": "bowsher_v_synar_1986",
        "name": "Bowsher v. Synar",
        "citation": "478 U.S. 714 (1986)",
        "year": 1986,
        "doctrine": "separation_of_powers",
        "summary": "Congress cannot reserve removal power over officer performing executive functions; violates separation of powers.",
        "holding": "Gramm-Rudman-Hollings Act unconstitutional; Comptroller General removable by Congress but exercises executive power.",
        "issue_tags": [
            "removal_power",
            "executive_functions",
            "comptroller_general",
            "separation_of_powers",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Separation of Powers",
        "relevance_to_audit": "Prevents congressional control of executive functions through removal power.",
    },
    {
        "case_id": "morrison_v_olson_1988",
        "name": "Morrison v. Olson",
        "citation": "487 U.S. 654 (1988)",
        "year": 1988,
        "doctrine": "separation_of_powers",
        "summary": "Independent counsel law constitutional; limited restrictions on President's removal power permissible.",
        "holding": "Ethics in Government Act permissibly limits President's removal power over independent counsel.",
        "issue_tags": [
            "independent_counsel",
            "removal_power",
            "good_cause",
            "executive_power",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "Article II",
        "relevance_to_audit": "Permits limited restrictions on presidential removal power for certain offices.",
    },
    {
        "case_id": "seila_law_v_cfpb_2020",
        "name": "Seila Law LLC v. Consumer Financial Protection Bureau",
        "citation": "140 S. Ct. 2183 (2020)",
        "year": 2020,
        "doctrine": "separation_of_powers",
        "summary": "Single-director CFPB structure with for-cause removal violates separation of powers; President must have removal power.",
        "holding": "CFPB's single-director structure insulated from presidential removal violates Article II.",
        "issue_tags": [
            "removal_power",
            "unitary_executive",
            "independent_agency",
            "for_cause",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Article II",
        "relevance_to_audit": "Strengthens presidential removal power; limits independence of single-director agencies.",
    },
]

if __name__ == "__main__":
    print(f"Additional CLEP-v2 cases: {len(ADDITIONAL_CLEP_V2_CASES)}")
