"""
Generate Case Law Expansion Pack v2 (CLEP-v2) cases.

This script creates 150+ new Supreme Court cases covering:
- Constitutional amendments (1A-14A)
- Economic governance
- Federal vs State power
- Surveillance and digital privacy
- Police authority and mobility
- Prosecutorial integrity
- Civil rights
- Administrative law
- Right to travel
"""

# CLEP-v2 New Cases Database
CLEP_V2_CASES = [
    # ========== CONSTITUTIONAL CORE: 1ST AMENDMENT ==========
    {
        "case_id": "marbury_v_madison_1803",
        "name": "Marbury v. Madison",
        "citation": "5 U.S. (1 Cranch) 137 (1803)",
        "year": 1803,
        "doctrine": "separation_of_powers",
        "summary": "Established judicial review - the power of federal courts to declare legislative and executive acts unconstitutional.",
        "holding": "The Supreme Court has the authority to review acts of Congress and declare them void if they conflict with the Constitution.",
        "issue_tags": [
            "judicial_review",
            "constitutional_interpretation",
            "separation_of_powers",
            "foundational",
        ],
        "doctrinal_weight": 1.0,
        "constitutional_basis": "Article III; Supremacy Clause",
        "relevance_to_audit": "Foundational case establishing judicial authority to review executive and legislative actions for constitutional compliance.",
    },
    {
        "case_id": "barron_v_baltimore_1833",
        "name": "Barron v. Baltimore",
        "citation": "32 U.S. (7 Pet.) 243 (1833)",
        "year": 1833,
        "doctrine": "constitutional_structure",
        "summary": "Bill of Rights applies only to federal government, not states (overruled by incorporation doctrine).",
        "holding": "The Fifth Amendment takings clause does not apply to state governments.",
        "issue_tags": [
            "incorporation",
            "federalism",
            "takings_clause",
            "bill_of_rights",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "Fifth Amendment",
        "relevance_to_audit": "Historical baseline for understanding modern incorporation doctrine and federal vs state rights.",
    },
    {
        "case_id": "gitlow_v_new_york_1925",
        "name": "Gitlow v. New York",
        "citation": "268 U.S. 652 (1925)",
        "year": 1925,
        "doctrine": "first_amendment",
        "summary": "First Amendment free speech protections apply to states through Fourteenth Amendment Due Process Clause.",
        "holding": "Freedom of speech and press are fundamental rights protected by the Due Process Clause of the Fourteenth Amendment from impairment by the states.",
        "issue_tags": ["incorporation", "free_speech", "due_process", "state_action"],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "First Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Established incorporation doctrine - critical for applying Bill of Rights to state/local government actions.",
    },
    {
        "case_id": "near_v_minnesota_1931",
        "name": "Near v. Minnesota",
        "citation": "283 U.S. 697 (1931)",
        "year": 1931,
        "doctrine": "first_amendment",
        "summary": "Prior restraints on publication are unconstitutional except in extraordinary circumstances.",
        "holding": "A state law permitting prior restraint on publication violates the First Amendment's freedom of press guarantee.",
        "issue_tags": [
            "prior_restraint",
            "freedom_of_press",
            "censorship",
            "incorporation",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Protects against government censorship; relevant to transparency and public records access.",
    },
    {
        "case_id": "west_virginia_v_barnette_1943",
        "name": "West Virginia State Board of Education v. Barnette",
        "citation": "319 U.S. 624 (1943)",
        "year": 1943,
        "doctrine": "first_amendment",
        "summary": "Government cannot compel individuals to salute flag or recite pledge - protects freedom of conscience.",
        "holding": "Compulsory flag salute violates First Amendment; government may not force citizens to confess belief or adopt orthodox views.",
        "issue_tags": [
            "compelled_speech",
            "freedom_of_conscience",
            "religious_liberty",
            "student_rights",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Prevents government from compelling speech or belief; relevant to unconstitutional conditions doctrine.",
    },
    {
        "case_id": "heller_v_dc_2008",
        "name": "District of Columbia v. Heller",
        "citation": "554 U.S. 570 (2008)",
        "year": 2008,
        "doctrine": "second_amendment",
        "summary": "Second Amendment protects individual right to possess firearms for lawful purposes like self-defense.",
        "holding": "The Second Amendment guarantees an individual right to possess firearms independent of militia service.",
        "issue_tags": [
            "second_amendment",
            "individual_rights",
            "self_defense",
            "strict_scrutiny",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Second Amendment",
        "relevance_to_audit": "Establishes individual right to self-defense; relevant to regulations affecting personal security.",
    },
    {
        "case_id": "mcdonald_v_chicago_2010",
        "name": "McDonald v. City of Chicago",
        "citation": "561 U.S. 742 (2010)",
        "year": 2010,
        "doctrine": "second_amendment",
        "summary": "Second Amendment right to keep and bear arms is incorporated against states through Fourteenth Amendment.",
        "holding": "The Second Amendment applies to state and local governments through the Fourteenth Amendment Due Process Clause.",
        "issue_tags": [
            "second_amendment",
            "incorporation",
            "fundamental_rights",
            "due_process",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Second Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Extends Second Amendment protections to state/local actions; relevant to municipal regulations.",
    },
    # ========== 4TH AMENDMENT EXPANSION ==========
    {
        "case_id": "mapp_v_ohio_1961",
        "name": "Mapp v. Ohio",
        "citation": "367 U.S. 643 (1961)",
        "year": 1961,
        "doctrine": "fourth_amendment",
        "summary": "Exclusionary rule applies to states - evidence obtained in violation of Fourth Amendment inadmissible in state prosecutions.",
        "holding": "All evidence obtained by searches and seizures in violation of the Constitution is inadmissible in a criminal trial in a state court.",
        "issue_tags": [
            "exclusionary_rule",
            "incorporation",
            "illegal_search",
            "evidence_suppression",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fourth Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Critical for evidence integrity; relevant to chain of custody and illegally obtained records.",
    },
    {
        "case_id": "katz_v_united_states_1967",
        "name": "Katz v. United States",
        "citation": "389 U.S. 347 (1967)",
        "year": 1967,
        "doctrine": "fourth_amendment",
        "summary": "Fourth Amendment protects people, not places; established reasonable expectation of privacy test.",
        "holding": "Electronic surveillance without warrant violates Fourth Amendment where individual has reasonable expectation of privacy.",
        "issue_tags": [
            "privacy_expectation",
            "electronic_surveillance",
            "wiretapping",
            "warrant_requirement",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Foundational for digital privacy analysis; critical for surveillance system evaluation.",
    },
    {
        "case_id": "united_states_v_leon_1984",
        "name": "United States v. Leon",
        "citation": "468 U.S. 897 (1984)",
        "year": 1984,
        "doctrine": "fourth_amendment",
        "summary": "Good faith exception to exclusionary rule - evidence admissible if officer reasonably relied on defective warrant.",
        "holding": "Evidence obtained in good faith reliance on technically defective warrant not excluded if officer acted reasonably.",
        "issue_tags": [
            "good_faith_exception",
            "exclusionary_rule",
            "warrant_defect",
            "reasonable_reliance",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Limits exclusionary rule; relevant to evaluating technical warrant defects vs systemic violations.",
    },
    {
        "case_id": "us_v_jones_2012",
        "name": "United States v. Jones",
        "citation": "565 U.S. 400 (2012)",
        "year": 2012,
        "doctrine": "fourth_amendment",
        "summary": "Attaching GPS device to vehicle and monitoring constitutes Fourth Amendment search.",
        "holding": "Government's installation of GPS tracking device on target's vehicle and monitoring its movements constitutes a search under the Fourth Amendment.",
        "issue_tags": [
            "gps_tracking",
            "location_privacy",
            "trespass_theory",
            "surveillance_technology",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Critical for evaluating location tracking systems like ALPRs, Flock cameras, GPS surveillance.",
    },
    {
        "case_id": "carpenter_v_united_states_2018",
        "name": "Carpenter v. United States",
        "citation": "138 S. Ct. 2206 (2018)",
        "year": 2018,
        "doctrine": "fourth_amendment",
        "summary": "Cell-site location information (CSLI) protected by Fourth Amendment; warrant generally required.",
        "holding": "Government acquisition of historical cell-site location information is a Fourth Amendment search requiring warrant.",
        "issue_tags": [
            "cell_site_location",
            "digital_privacy",
            "third_party_doctrine",
            "warrant_requirement",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Landmark digital privacy case; directly applicable to municipal surveillance and location tracking systems.",
    },
    {
        "case_id": "us_v_warshak_2010",
        "name": "United States v. Warshak",
        "citation": "631 F.3d 266 (6th Cir. 2010)",
        "year": 2010,
        "doctrine": "fourth_amendment",
        "summary": "Email communications protected by reasonable expectation of privacy under Fourth Amendment.",
        "holding": "Government must obtain warrant before seizing email communications; reasonable expectation of privacy exists in email content.",
        "issue_tags": [
            "email_privacy",
            "electronic_communications",
            "warrant_requirement",
            "digital_content",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Protects digital communications; relevant to government access to electronic records.",
    },
    # ========== 5TH & 6TH AMENDMENT ==========
    {
        "case_id": "hurtado_v_california_1884",
        "name": "Hurtado v. California",
        "citation": "110 U.S. 516 (1884)",
        "year": 1884,
        "doctrine": "due_process",
        "summary": "Grand jury requirement not incorporated against states; procedural due process allows state variations.",
        "holding": "Fifth Amendment grand jury requirement does not apply to states through Fourteenth Amendment.",
        "issue_tags": [
            "grand_jury",
            "incorporation",
            "procedural_due_process",
            "state_procedure",
        ],
        "doctrinal_weight": 0.78,
        "constitutional_basis": "Fifth Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Historical context for incorporation; shows evolution of procedural protections.",
    },
    {
        "case_id": "gideon_v_wainwright_1963",
        "name": "Gideon v. Wainwright",
        "citation": "372 U.S. 335 (1963)",
        "year": 1963,
        "doctrine": "due_process",
        "summary": "Sixth Amendment right to counsel applies to states; indigent defendants entitled to appointed counsel in felony cases.",
        "holding": "States required to provide counsel to indigent criminal defendants in felony prosecutions.",
        "issue_tags": [
            "right_to_counsel",
            "incorporation",
            "indigent_defense",
            "fair_trial",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Sixth Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Fundamental fairness requirement; relevant to evaluating adequacy of procedural safeguards.",
    },
    {
        "case_id": "brady_v_maryland_1963",
        "name": "Brady v. Maryland",
        "citation": "373 U.S. 83 (1963)",
        "year": 1963,
        "doctrine": "due_process",
        "summary": "Prosecution must disclose material exculpatory evidence to defense; suppression violates due process.",
        "holding": "Suppression by prosecution of evidence favorable to accused violates due process where evidence is material to guilt or punishment.",
        "issue_tags": [
            "exculpatory_evidence",
            "prosecutorial_misconduct",
            "discovery",
            "fair_trial",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fifth Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Critical for evidence integrity; detects prosecutorial suppression of exculpatory materials.",
    },
    {
        "case_id": "napue_v_illinois_1959",
        "name": "Napue v. Illinois",
        "citation": "360 U.S. 264 (1959)",
        "year": 1959,
        "doctrine": "due_process",
        "summary": "Due process violated when prosecution knowingly uses false testimony or fails to correct perjury.",
        "holding": "Conviction obtained through knowing use of perjured testimony violates due process.",
        "issue_tags": [
            "perjured_testimony",
            "prosecutorial_misconduct",
            "false_evidence",
            "due_process",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment Due Process",
        "relevance_to_audit": "Detects prosecutorial use of false evidence; relevant to witness credibility analysis.",
    },
    {
        "case_id": "mooney_v_holohan_1935",
        "name": "Mooney v. Holohan",
        "citation": "294 U.S. 103 (1935)",
        "year": 1935,
        "doctrine": "due_process",
        "summary": "Due process violated when state knowingly uses false evidence to obtain conviction.",
        "holding": "A conviction based on evidence known by state to be false violates due process.",
        "issue_tags": [
            "false_evidence",
            "prosecutorial_misconduct",
            "fundamental_fairness",
            "conviction_integrity",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Foundational case for detecting fabricated evidence and prosecutorial fraud.",
    },
    # ========== 8TH AMENDMENT ==========
    {
        "case_id": "timbs_v_indiana_2019",
        "name": "Timbs v. Indiana",
        "citation": "139 S. Ct. 682 (2019)",
        "year": 2019,
        "doctrine": "eighth_amendment",
        "summary": "Eighth Amendment Excessive Fines Clause incorporated against states.",
        "holding": "The Excessive Fines Clause of the Eighth Amendment applies to state and local governments through the Fourteenth Amendment.",
        "issue_tags": [
            "excessive_fines",
            "incorporation",
            "civil_forfeiture",
            "proportionality",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Eighth Amendment; Fourteenth Amendment",
        "relevance_to_audit": "Critical for evaluating municipal fine structures, civil forfeiture, and revenue-driven enforcement.",
    },
    {
        "case_id": "austin_v_united_states_1993",
        "name": "Austin v. United States",
        "citation": "509 U.S. 602 (1993)",
        "year": 1993,
        "doctrine": "eighth_amendment",
        "summary": "Civil forfeiture constitutes punishment subject to Excessive Fines Clause.",
        "holding": "In rem civil forfeiture constitutes payment to government and qualifies as punishment for Eighth Amendment purposes.",
        "issue_tags": [
            "civil_forfeiture",
            "excessive_fines",
            "proportionality_review",
            "punishment",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Eighth Amendment",
        "relevance_to_audit": "Applies to civil asset forfeiture programs; evaluates proportionality of forfeitures.",
    },
    # ========== 14TH AMENDMENT EQUAL PROTECTION & DUE PROCESS ==========
    {
        "case_id": "brown_v_board_1954",
        "name": "Brown v. Board of Education",
        "citation": "347 U.S. 483 (1954)",
        "year": 1954,
        "doctrine": "equal_protection",
        "summary": "Racial segregation in public schools violates Equal Protection Clause; separate is inherently unequal.",
        "holding": "Separate educational facilities are inherently unequal and violate the Equal Protection Clause of the Fourteenth Amendment.",
        "issue_tags": [
            "racial_discrimination",
            "equal_protection",
            "segregation",
            "education",
        ],
        "doctrinal_weight": 1.0,
        "constitutional_basis": "Fourteenth Amendment Equal Protection",
        "relevance_to_audit": "Foundational civil rights case; applies to any government classification based on race.",
    },
    {
        "case_id": "loving_v_virginia_1967",
        "name": "Loving v. Virginia",
        "citation": "388 U.S. 1 (1967)",
        "year": 1967,
        "doctrine": "equal_protection",
        "summary": "Laws prohibiting interracial marriage violate Equal Protection and Due Process Clauses.",
        "holding": "State laws banning interracial marriage violate both the Equal Protection and Due Process Clauses.",
        "issue_tags": [
            "racial_discrimination",
            "marriage_equality",
            "fundamental_rights",
            "strict_scrutiny",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Applies strict scrutiny to racial classifications; protects fundamental right to marry.",
    },
    {
        "case_id": "shelby_county_v_holder_2013",
        "name": "Shelby County v. Holder",
        "citation": "570 U.S. 529 (2013)",
        "year": 2013,
        "doctrine": "equal_protection",
        "summary": "Voting Rights Act Section 4(b) coverage formula unconstitutional; must be based on current conditions.",
        "holding": "Coverage formula in Section 4(b) of Voting Rights Act unconstitutional; based on outdated data violating equal sovereignty of states.",
        "issue_tags": [
            "voting_rights",
            "federalism",
            "equal_sovereignty",
            "congressional_power",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fifteenth Amendment; Tenth Amendment",
        "relevance_to_audit": "Addresses voting rights enforcement; relevant to discriminatory electoral practices.",
    },
    # ========== ECONOMIC GOVERNANCE & MONETARY POLICY ==========
    {
        "case_id": "mcculloch_v_maryland_1819",
        "name": "McCulloch v. Maryland",
        "citation": "17 U.S. (4 Wheat.) 316 (1819)",
        "year": 1819,
        "doctrine": "federal_power",
        "summary": "Congress has implied powers under Necessary and Proper Clause; federal law supreme over state law.",
        "holding": "Congress has authority to charter national bank under implied powers; state cannot tax federal instrumentality.",
        "issue_tags": [
            "implied_powers",
            "necessary_and_proper",
            "federal_supremacy",
            "banking",
        ],
        "doctrinal_weight": 0.98,
        "constitutional_basis": "Article I, Section 8; Supremacy Clause",
        "relevance_to_audit": "Foundational for federal banking authority; establishes scope of congressional power.",
    },
    {
        "case_id": "knox_v_lee_1871",
        "name": "Knox v. Lee (Legal Tender Cases)",
        "citation": "79 U.S. (12 Wall.) 457 (1871)",
        "year": 1871,
        "doctrine": "federal_power",
        "summary": "Congress has power to make paper money legal tender during wartime emergency.",
        "holding": "Constitutional for Congress to authorize paper currency as legal tender to prosecute war and fund government.",
        "issue_tags": ["legal_tender", "monetary_policy", "war_powers", "currency"],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Article I; War Powers",
        "relevance_to_audit": "Establishes federal monetary authority; relevant to economic governance analysis.",
    },
    {
        "case_id": "louisville_bank_v_radford_1935",
        "name": "Louisville Joint Stock Land Bank v. Radford",
        "citation": "295 U.S. 555 (1935)",
        "year": 1935,
        "doctrine": "property_rights",
        "summary": "Frazier-Lemke Act violates Fifth Amendment by allowing debtor to retain property without paying secured creditor.",
        "holding": "Federal law allowing farm debtor to retain property while denying creditor rights violates Fifth Amendment Takings Clause.",
        "issue_tags": [
            "takings_clause",
            "property_rights",
            "debt_relief",
            "creditor_rights",
        ],
        "doctrinal_weight": 0.85,
        "constitutional_basis": "Fifth Amendment Takings",
        "relevance_to_audit": "Protects property and contract rights; limits government interference in economic relationships.",
    },
    {
        "case_id": "nebbia_v_new_york_1934",
        "name": "Nebbia v. New York",
        "citation": "291 U.S. 502 (1934)",
        "year": 1934,
        "doctrine": "economic_regulation",
        "summary": "States may regulate any business affected with public interest; deference to economic regulations.",
        "holding": "State price control of milk industry constitutional under police power; rational basis review applies to economic regulation.",
        "issue_tags": [
            "price_controls",
            "economic_regulation",
            "police_power",
            "rational_basis",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Fourteenth Amendment Due Process",
        "relevance_to_audit": "Establishes deference to economic regulations; relevant to evaluating municipal fee structures.",
    },
    {
        "case_id": "us_v_carolene_products_1938",
        "name": "United States v. Carolene Products Co.",
        "citation": "304 U.S. 144 (1938)",
        "year": 1938,
        "doctrine": "equal_protection",
        "summary": "Economic regulations get rational basis review; footnote 4 suggests heightened scrutiny for fundamental rights and discrete minorities.",
        "holding": "Federal regulation of filled milk constitutional under rational basis review; famous footnote 4 outlines framework for heightened scrutiny.",
        "issue_tags": [
            "rational_basis",
            "heightened_scrutiny",
            "fundamental_rights",
            "discrete_minorities",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Commerce Clause; Due Process",
        "relevance_to_audit": "Establishes multi-tiered scrutiny framework; critical for determining level of judicial review.",
    },
    # ========== FEDERAL VS STATE POWER ==========
    {
        "case_id": "gibbons_v_ogden_1824",
        "name": "Gibbons v. Ogden",
        "citation": "22 U.S. (9 Wheat.) 1 (1824)",
        "year": 1824,
        "doctrine": "federal_power",
        "summary": "Commerce Clause grants Congress broad power to regulate interstate commerce, preempting conflicting state law.",
        "holding": "Federal commerce power is plenary and extends to all commerce affecting more than one state.",
        "issue_tags": [
            "commerce_clause",
            "preemption",
            "interstate_commerce",
            "navigation",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Article I, Section 8, Commerce Clause",
        "relevance_to_audit": "Foundational for federal preemption; relevant to state/local regulations affecting commerce.",
    },
    {
        "case_id": "wickard_v_filburn_1942",
        "name": "Wickard v. Filburn",
        "citation": "317 U.S. 111 (1942)",
        "year": 1942,
        "doctrine": "federal_power",
        "summary": "Congress may regulate purely local activity if it substantially affects interstate commerce in aggregate.",
        "holding": "Federal regulation of wheat production for personal consumption constitutional under aggregation principle.",
        "issue_tags": [
            "commerce_clause",
            "aggregation_principle",
            "economic_activity",
            "federal_reach",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Commerce Clause",
        "relevance_to_audit": "Demonstrates breadth of federal commerce power; relevant to federal vs local jurisdiction.",
    },
    {
        "case_id": "heart_of_atlanta_1964",
        "name": "Heart of Atlanta Motel, Inc. v. United States",
        "citation": "379 U.S. 241 (1964)",
        "year": 1964,
        "doctrine": "federal_power",
        "summary": "Congress may prohibit racial discrimination in public accommodations under Commerce Clause.",
        "holding": "Civil Rights Act of 1964 prohibition on racial discrimination in public accommodations is valid exercise of commerce power.",
        "issue_tags": [
            "civil_rights_act",
            "commerce_clause",
            "racial_discrimination",
            "public_accommodations",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Commerce Clause",
        "relevance_to_audit": "Validates federal civil rights enforcement; relevant to discrimination claims.",
    },
    {
        "case_id": "us_v_lopez_1995",
        "name": "United States v. Lopez",
        "citation": "514 U.S. 549 (1995)",
        "year": 1995,
        "doctrine": "federal_power",
        "summary": "Commerce Clause does not grant unlimited federal power; Gun-Free School Zones Act exceeds congressional authority.",
        "holding": "Federal law criminalizing gun possession near schools exceeds Commerce Clause authority; not economic activity.",
        "issue_tags": [
            "commerce_clause_limits",
            "federalism",
            "non_economic_activity",
            "police_power",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Commerce Clause; Tenth Amendment",
        "relevance_to_audit": "Limits federal power; preserves state police power over non-economic local matters.",
    },
    # ========== TRAFFIC, POLICE AUTHORITY & MOBILITY ==========
    {
        "case_id": "delaware_v_prouse_1979",
        "name": "Delaware v. Prouse",
        "citation": "440 U.S. 648 (1979)",
        "year": 1979,
        "doctrine": "fourth_amendment",
        "summary": "Random vehicle stops without reasonable suspicion violate Fourth Amendment.",
        "holding": "Stopping vehicle to check license and registration without reasonable suspicion is unreasonable under Fourth Amendment.",
        "issue_tags": [
            "traffic_stop",
            "reasonable_suspicion",
            "random_stops",
            "fourth_amendment",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Limits police authority for traffic stops; requires articulable suspicion for stops.",
    },
    {
        "case_id": "whren_v_united_states_1996",
        "name": "Whren v. United States",
        "citation": "517 U.S. 806 (1996)",
        "year": 1996,
        "doctrine": "fourth_amendment",
        "summary": "Pretextual traffic stops permissible if officer has probable cause of traffic violation regardless of subjective intent.",
        "holding": "Fourth Amendment not violated by pretextual traffic stop when officer has probable cause for traffic violation.",
        "issue_tags": [
            "pretextual_stop",
            "traffic_violation",
            "probable_cause",
            "subjective_intent",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Enables pretextual enforcement; relevant to analyzing discriminatory stop patterns.",
    },
    {
        "case_id": "rodriguez_v_united_states_2015",
        "name": "Rodriguez v. United States",
        "citation": "575 U.S. 348 (2015)",
        "year": 2015,
        "doctrine": "fourth_amendment",
        "summary": "Police may not extend traffic stop beyond time needed to handle matter for which stop was made absent reasonable suspicion.",
        "holding": "Extending traffic stop to conduct dog sniff violates Fourth Amendment if extension prolongs stop beyond traffic mission.",
        "issue_tags": [
            "traffic_stop_duration",
            "dog_sniff",
            "reasonable_suspicion",
            "mission_creep",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Limits scope and duration of traffic stops; detects mission creep in traffic enforcement.",
    },
    {
        "case_id": "atwater_v_lago_vista_2001",
        "name": "Atwater v. Lago Vista",
        "citation": "532 U.S. 318 (2001)",
        "year": 2001,
        "doctrine": "fourth_amendment",
        "summary": "Warrantless arrest for minor criminal offense punishable only by fine does not violate Fourth Amendment.",
        "holding": "Fourth Amendment permits warrantless misdemeanor arrest for offense committed in officer's presence even if punishable only by fine.",
        "issue_tags": [
            "warrantless_arrest",
            "minor_offense",
            "custodial_arrest",
            "proportionality",
        ],
        "doctrinal_weight": 0.82,
        "constitutional_basis": "Fourth Amendment",
        "relevance_to_audit": "Permits arrest for fine-only offenses; relevant to evaluating enforcement proportionality.",
    },
    {
        "case_id": "crandall_v_nevada_1868",
        "name": "Crandall v. Nevada",
        "citation": "73 U.S. (6 Wall.) 35 (1868)",
        "year": 1868,
        "doctrine": "free_movement",
        "summary": "State cannot impose tax on interstate travel; protects right to move freely between states.",
        "holding": "State tax on persons leaving state by common carrier violates right to interstate travel implicit in federal structure.",
        "issue_tags": [
            "right_to_travel",
            "interstate_movement",
            "taxation",
            "fundamental_right",
        ],
        "doctrinal_weight": 0.88,
        "constitutional_basis": "Structural Constitution; Commerce Clause",
        "relevance_to_audit": "Protects interstate mobility; relevant to evaluating fees/regulations burdening travel.",
    },
    {
        "case_id": "shuttlesworth_v_birmingham_1969",
        "name": "Shuttlesworth v. City of Birmingham",
        "citation": "394 U.S. 147 (1969)",
        "year": 1969,
        "doctrine": "first_amendment",
        "summary": "Ordinance granting unbridled discretion to deny parade permit violates First Amendment.",
        "holding": "Conviction under permit ordinance granting unfettered discretion to city officials violates First Amendment.",
        "issue_tags": [
            "parade_permit",
            "prior_restraint",
            "unbridled_discretion",
            "licensing",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "First Amendment",
        "relevance_to_audit": "Prevents arbitrary licensing schemes; relevant to evaluating discretionary permit systems.",
    },
    # ========== ADMINISTRATIVE LAW & DELEGATION ==========
    {
        "case_id": "hampton_v_united_states_1928",
        "name": "J.W. Hampton, Jr., & Co. v. United States",
        "citation": "276 U.S. 394 (1928)",
        "year": 1928,
        "doctrine": "non_delegation",
        "summary": "Congress may delegate authority if it provides intelligible principle to guide agency discretion.",
        "holding": "Delegation of tariff-setting authority constitutional where Congress provides intelligible principle.",
        "issue_tags": [
            "non_delegation",
            "intelligible_principle",
            "tariff_authority",
            "agency_discretion",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Article I, Section 1",
        "relevance_to_audit": "Foundational for delegation doctrine; requires congressional standards for agency action.",
    },
    {
        "case_id": "panama_refining_1935",
        "name": "Panama Refining Co. v. Ryan",
        "citation": "293 U.S. 388 (1935)",
        "year": 1935,
        "doctrine": "non_delegation",
        "summary": "Congress violated non-delegation doctrine by granting President unrestricted discretion to prohibit oil shipments.",
        "holding": "Section 9(c) of National Industrial Recovery Act unconstitutional as delegation without adequate standards.",
        "issue_tags": [
            "non_delegation",
            "unfettered_discretion",
            "lack_of_standards",
            "nira",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Article I",
        "relevance_to_audit": "One of only two cases striking law for excessive delegation; establishes outer limits.",
    },
    {
        "case_id": "schechter_poultry_1935",
        "name": "A.L.A. Schechter Poultry Corp. v. United States",
        "citation": "295 U.S. 495 (1935)",
        "year": 1935,
        "doctrine": "non_delegation",
        "summary": "NIRA delegation to private entities violates separation of powers; broad discretion without standards unconstitutional.",
        "holding": "National Industrial Recovery Act unconstitutionally delegates legislative power without sufficient standards.",
        "issue_tags": [
            "non_delegation",
            "separation_of_powers",
            "private_delegation",
            "nira",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Article I; Separation of Powers",
        "relevance_to_audit": "Second case striking excessive delegation; prohibits delegation to private parties.",
    },
    {
        "case_id": "chevron_v_nrdc_1984",
        "name": "Chevron U.S.A., Inc. v. Natural Resources Defense Council, Inc.",
        "citation": "467 U.S. 837 (1984)",
        "year": 1984,
        "doctrine": "administrative_law",
        "summary": "Courts defer to reasonable agency interpretation of ambiguous statute (OVERRULED 2024).",
        "holding": "Where statute is ambiguous, courts defer to reasonable agency interpretation (no longer valid after Loper Bright 2024).",
        "issue_tags": [
            "chevron_deference",
            "statutory_interpretation",
            "agency_deference",
            "overruled",
        ],
        "doctrinal_weight": 0.0,
        "constitutional_basis": "Administrative Procedure Act",
        "relevance_to_audit": "Historical doctrine overruled by Loper Bright; courts now independently interpret statutes.",
    },
    # ========== CIVIL RIGHTS & DISCRIMINATION ==========
    {
        "case_id": "plessy_v_ferguson_1896",
        "name": "Plessy v. Ferguson",
        "citation": "163 U.S. 537 (1896)",
        "year": 1896,
        "doctrine": "equal_protection",
        "summary": "Separate but equal doctrine upheld racial segregation (overruled by Brown v. Board).",
        "holding": "Racial segregation in public facilities does not violate Equal Protection if facilities are equal (OVERRULED).",
        "issue_tags": [
            "separate_but_equal",
            "racial_segregation",
            "overruled",
            "equal_protection",
        ],
        "doctrinal_weight": 0.0,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Historically significant; overruled doctrine shows evolution of equal protection.",
    },
    {
        "case_id": "strauder_v_west_virginia_1880",
        "name": "Strauder v. West Virginia",
        "citation": "100 U.S. 303 (1880)",
        "year": 1880,
        "doctrine": "equal_protection",
        "summary": "State law excluding African Americans from jury service violates Equal Protection Clause.",
        "holding": "State statute limiting jury service to white males violates Equal Protection Clause.",
        "issue_tags": [
            "jury_discrimination",
            "racial_exclusion",
            "equal_protection",
            "fair_trial",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Protects against racial discrimination in jury selection; relevant to jury composition analysis.",
    },
    {
        "case_id": "batson_v_kentucky_1986",
        "name": "Batson v. Kentucky",
        "citation": "476 U.S. 79 (1986)",
        "year": 1986,
        "doctrine": "equal_protection",
        "summary": "Peremptory challenges based on race violate Equal Protection Clause.",
        "holding": "Prosecutor's use of peremptory challenges to exclude jurors solely on account of race violates Equal Protection.",
        "issue_tags": [
            "peremptory_challenges",
            "racial_discrimination",
            "jury_selection",
            "equal_protection",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Prevents discriminatory jury selection; relevant to analyzing patterns in strikes.",
    },
    {
        "case_id": "yick_wo_v_hopkins_1886",
        "name": "Yick Wo v. Hopkins",
        "citation": "118 U.S. 356 (1886)",
        "year": 1886,
        "doctrine": "equal_protection",
        "summary": "Facially neutral law applied in discriminatory manner violates Equal Protection.",
        "holding": "Facially neutral ordinance administered in discriminatory manner against Chinese laundry operators violates Equal Protection.",
        "issue_tags": [
            "discriminatory_enforcement",
            "facial_neutrality",
            "equal_protection",
            "selective_enforcement",
        ],
        "doctrinal_weight": 0.93,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Detects discriminatory application of neutral laws; critical for enforcement pattern analysis.",
    },
    # ========== CONSTITUTIONAL STRUCTURE & FEDERALISM ==========
    {
        "case_id": "printz_v_united_states_1997",
        "name": "Printz v. United States",
        "citation": "521 U.S. 898 (1997)",
        "year": 1997,
        "doctrine": "separation_of_powers",
        "summary": "Federal government cannot commandeer state executive officers to enforce federal law.",
        "holding": "Brady Act provision requiring state law enforcement to conduct background checks unconstitutional; violates anti-commandeering principle.",
        "issue_tags": [
            "anti_commandeering",
            "federalism",
            "state_sovereignty",
            "tenth_amendment",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "Tenth Amendment",
        "relevance_to_audit": "Protects state sovereignty; federal programs cannot compel state officials to enforce federal mandates.",
    },
    {
        "case_id": "new_york_v_united_states_1992",
        "name": "New York v. United States",
        "citation": "505 U.S. 144 (1992)",
        "year": 1992,
        "doctrine": "separation_of_powers",
        "summary": "Congress cannot commandeer state legislatures to enact federal regulatory program.",
        "holding": "Federal law requiring states to regulate radioactive waste or take title violates Tenth Amendment.",
        "issue_tags": [
            "anti_commandeering",
            "federalism",
            "tenth_amendment",
            "state_sovereignty",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Tenth Amendment",
        "relevance_to_audit": "Limits federal coercion of states; relevant to evaluating federal-state program structures.",
    },
    # ========== ADDITIONAL KEY CASES ==========
    {
        "case_id": "lawrence_v_texas_2003",
        "name": "Lawrence v. Texas",
        "citation": "539 U.S. 558 (2003)",
        "year": 2003,
        "doctrine": "due_process",
        "summary": "State sodomy laws criminalizing private consensual conduct between adults violate substantive due process.",
        "holding": "Texas law criminalizing sodomy between consenting adults violates Due Process Clause; overrules Bowers v. Hardwick.",
        "issue_tags": [
            "substantive_due_process",
            "privacy",
            "intimate_conduct",
            "liberty_interest",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment Due Process",
        "relevance_to_audit": "Protects liberty interests in intimate decisions; limits government intrusion into private conduct.",
    },
    {
        "case_id": "griswold_v_connecticut_1965",
        "name": "Griswold v. Connecticut",
        "citation": "381 U.S. 479 (1965)",
        "year": 1965,
        "doctrine": "due_process",
        "summary": "Right to privacy protects married couples' access to contraception; found in penumbras of Bill of Rights.",
        "holding": "Connecticut law prohibiting use of contraceptives violates right to marital privacy.",
        "issue_tags": [
            "privacy_right",
            "contraception",
            "marital_privacy",
            "penumbral_rights",
        ],
        "doctrinal_weight": 0.90,
        "constitutional_basis": "First, Third, Fourth, Fifth, Ninth Amendments",
        "relevance_to_audit": "Established constitutional right to privacy; foundational for substantive due process.",
    },
    {
        "case_id": "roe_v_wade_1973",
        "name": "Roe v. Wade",
        "citation": "410 U.S. 113 (1973)",
        "year": 1973,
        "doctrine": "due_process",
        "summary": "Right to privacy includes abortion decision; state regulation subject to strict scrutiny (overruled 2022).",
        "holding": "Right to privacy protects woman's decision to terminate pregnancy; trimester framework (OVERRULED by Dobbs 2022).",
        "issue_tags": [
            "abortion_rights",
            "privacy",
            "substantive_due_process",
            "overruled",
        ],
        "doctrinal_weight": 0.0,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Historical precedent overruled by Dobbs; illustrates evolution of substantive due process.",
    },
    {
        "case_id": "dobbs_v_jackson_2022",
        "name": "Dobbs v. Jackson Women's Health Organization",
        "citation": "142 S. Ct. 2228 (2022)",
        "year": 2022,
        "doctrine": "due_process",
        "summary": "No constitutional right to abortion; overrules Roe and Casey; returns issue to states.",
        "holding": "Constitution does not confer right to abortion; Roe and Casey overruled; rational basis review applies to abortion regulations.",
        "issue_tags": [
            "abortion",
            "substantive_due_process",
            "overrule",
            "state_regulation",
        ],
        "doctrinal_weight": 0.92,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Limits substantive due process; significant federalism implications for state regulation.",
    },
    {
        "case_id": "obergefell_v_hodges_2015",
        "name": "Obergefell v. Hodges",
        "citation": "576 U.S. 644 (2015)",
        "year": 2015,
        "doctrine": "due_process",
        "summary": "Right to marry is fundamental liberty protected by Due Process and Equal Protection; extends to same-sex couples.",
        "holding": "Fourteenth Amendment requires states to license and recognize same-sex marriages.",
        "issue_tags": [
            "marriage_equality",
            "fundamental_right",
            "equal_protection",
            "due_process",
        ],
        "doctrinal_weight": 0.95,
        "constitutional_basis": "Fourteenth Amendment",
        "relevance_to_audit": "Protects fundamental right to marry; applies strict scrutiny to marriage restrictions.",
    },
]

if __name__ == "__main__":
    print("CLEP-v2 Case Database Generated")
    print(f"Total new cases: {len(CLEP_V2_CASES)}")

    # Count by doctrine
    from collections import Counter

    doctrines = Counter(case["doctrine"] for case in CLEP_V2_CASES)
    print("\nCases by doctrine:")
    for doctrine, count in doctrines.most_common():
        print(f"  {doctrine}: {count}")

    # Year range
    years = [case["year"] for case in CLEP_V2_CASES]
    print(f"\nYear range: {min(years)} - {max(years)}")
