# src/oraculus_di_auditor/aei19/schemas.py
"""Pydantic models for Phase 19 (AEI-19) data structures."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class UIFState(BaseModel):
    """Unified Intelligence Field state representation."""

    uif_id: str = Field(..., description="SHA256 hash of UIF construction")
    dimension: int = Field(142, description="Dimensionality of intelligence tensor")
    field_vector: dict[str, float] = Field(
        ..., description="142-dimensional intelligence vector"
    )
    phase_contributions: dict[str, dict[str, Any]] = Field(
        ..., description="Contribution from each phase (12-18)"
    )
    harmonization_pressure: float = Field(
        ..., ge=0.0, le=1.0, description="EMCS-16 harmonization influence"
    )
    ethical_warp: float = Field(
        ..., ge=0.0, le=1.0, description="REC-17 ethical influence"
    )
    governance_weight: float = Field(
        ..., ge=0.0, le=1.0, description="RGK-18 governance influence"
    )


class InsightPacket(BaseModel):
    """Individual insight generated by ISE-19."""

    insight_id: str = Field(..., description="Unique insight identifier")
    insight_type: str = Field(
        ...,
        description="Type: analytic, contextual, emergent, counterfactual",
    )
    content: str = Field(..., description="Human-readable insight text")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in insight")
    source_phases: list[str] = Field(
        ..., description="Phases contributing to this insight"
    )
    structured_data: dict[str, Any] = Field(
        default_factory=dict, description="Machine-readable insight data"
    )


class AlignmentReport(BaseModel):
    """Ethical and governance alignment report from EGA-19."""

    alignment_id: str = Field(..., description="SHA256 hash of alignment check")
    rec17_compliant: bool = Field(..., description="REC-17 ethical compliance")
    rgk18_compliant: bool = Field(..., description="RGK-18 governance compliance")
    ethical_score: float = Field(
        ..., ge=0.0, le=1.0, description="Overall ethical alignment"
    )
    governance_score: float = Field(
        ..., ge=0.0, le=1.0, description="Overall governance alignment"
    )
    violations: list[str] = Field(
        default_factory=list, description="List of violations detected"
    )
    recommendations: list[str] = Field(
        default_factory=list, description="Alignment improvement suggestions"
    )


class ScenarioStep(BaseModel):
    """Single step in deterministic scenario simulation."""

    step_number: int = Field(..., description="Step index (1-3)")
    state_vector: dict[str, float] = Field(
        ..., description="Projected state at this step"
    )
    ethical_delta: float = Field(
        ..., description="Change in ethical score from previous step"
    )
    governance_delta: float = Field(
        ..., description="Change in governance score from previous step"
    )
    risk_level: str = Field(
        ..., description="Risk assessment: none, low, moderate, high"
    )


class ScenarioMap(BaseModel):
    """Complete deterministic scenario simulation from DSS-19."""

    scenario_id: str = Field(..., description="SHA256 hash of scenario")
    steps: list[ScenarioStep] = Field(..., description="Scenario evolution steps (1-3)")
    trajectory_type: str = Field(
        ...,
        description="Trajectory classification: stable, improving, degrading",
    )
    reversibility: bool = Field(
        ..., description="Whether scenario changes are reversible"
    )
    critical_points: list[int] = Field(
        default_factory=list, description="Step numbers with critical changes"
    )


class AEI19Result(BaseModel):
    """Final Applied Intelligence Packet from AIP-19."""

    result_id: str = Field(..., description="Unique result identifier")
    explanation: str = Field(..., description="Human-readable narrative explanation")
    structured_packet: dict[str, Any] = Field(
        ..., description="Machine-readable intelligence packet"
    )
    counterfactuals: list[str] = Field(
        ..., description="Alternative scenario descriptions"
    )
    ethical_basis: dict[str, Any] = Field(
        ..., description="Ethical reasoning foundation"
    )
    governance_basis: dict[str, Any] = Field(
        ..., description="Governance reasoning foundation"
    )
    determinism_signature: str = Field(
        ..., description="SHA256 signature for determinism verification"
    )
    reversibility_protocol: str = Field(
        ..., description="Instructions for reversing this intelligence"
    )


class Phase19Result(BaseModel):
    """Complete Phase 19 output structure."""

    uif_19_state: UIFState = Field(..., description="Unified Intelligence Field state")
    insight_packets: list[InsightPacket] = Field(..., description="Generated insights")
    alignment_report: AlignmentReport = Field(
        ..., description="Ethical-governance alignment report"
    )
    scenario_map: ScenarioMap = Field(
        ..., description="Deterministic scenario simulation"
    )
    aei19_result: AEI19Result = Field(
        ..., description="Final applied intelligence packet"
    )
    provenance: dict[str, Any] = Field(..., description="Full provenance metadata")
