"""Plain-language explainer generator for community education.

Converts ODIA legal findings into accessible, jargon-free explanations
suitable for:

  - Community meeting handouts
  - Public comment submissions
  - Social media advocacy threads
  - Multilingual translation source text (simple vocabulary lowers AI
    translation error rate)
  - Non-lawyer advocacy training materials

The explainer avoids legal jargon wherever possible, and when a legal
term must be used it is immediately defined in parentheses.

Usage::

    from odia_legal.reports.explainer import generate_explainer

    explainer = generate_explainer(
        doc_meta={"title": "ALPR Policy 2024", "agency": "Anytown PD"},
        findings=findings_list,
        audience="community",   # 'community' | 'council' | 'media'
    )
    print(explainer.to_text())
    print(explainer.to_html())
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from typing import Any, Literal

Audience = Literal["community", "council", "media"]

_LINE_WIDTH = 70
_INDENT = "  "

# ---------------------------------------------------------------------------
# Jargon → plain-language translations
# ---------------------------------------------------------------------------

_JARGON: dict[str, str] = {
    "CPRA": "California Public Records Act (the state law that gives residents the right to request government documents)",
    "ALPR": "automated license plate readers (cameras that photograph and track every passing vehicle)",
    "CSLI": "cell-site location information (records of where your phone connected to cell towers)",
    "AB 481": "California Assembly Bill 481 (a 2021 law requiring police to get public approval before buying surveillance equipment)",
    "JAG": "Justice Assistance Grant (federal money given to police departments)",
    "§": "section",
    "Gov. Code": "Government Code",
    "Pen. Code": "Penal Code",
    "Civ. Code": "Civil Code",
    "subd.": "subdivision",
    "balancing test": "balancing test (when a judge weighs competing interests to decide a case)",
    "supplanting": "replacing existing local funding with federal grant money (which is not allowed)",
    "subrecipient": "a smaller organization that receives part of a federal grant",
    "catch-all exemption": "a broad legal loophole that lets agencies refuse to share records if they claim it's 'not in the public interest'",
    "deliberative process": "internal government discussions that agencies sometimes use to justify hiding records",
}

# Per-layer plain-language category names
_LAYER_LABELS: dict[str, str] = {
    "l1_statutory_applicability": "Laws that apply to this document",
    "l2_procedural_compliance": "Procedures the agency may have skipped",
    "l3_exemption_misapplication": "Public records requests that may have been wrongly denied",
    "l5_federal_grant_compliance": "Problems with how federal grant money is being used",
    "l6_constitutional_implication": "Possible violations of your constitutional rights",
    "l8_case_law_currency": "Court decisions the agency may be ignoring",
    "l9_recodification": "Cases where the agency cited an outdated law number",
    "l10_balancing_test": "Cases where the agency did not properly weigh competing interests",
}

# Severity → plain impact statement
_SEVERITY_PLAIN: dict[str, str] = {
    "high": "SERIOUS CONCERN",
    "medium": "WORTH INVESTIGATING",
    "low": "INFORMATIONAL",
}

# Per-severity action guidance
_SEVERITY_ACTION: dict[str, str] = {
    "high": "You or your organization may want to consult an attorney or file a formal complaint.",
    "medium": "Consider asking the agency for clarification at the next public meeting or via a public records request.",
    "low": "This is useful background information. No immediate action is required.",
}


# ---------------------------------------------------------------------------
# Audience intro templates
# ---------------------------------------------------------------------------

_INTROS: dict[str, str] = {
    "community": (
        "This report was automatically generated by ODIA (Oraculus Decimus "
        "Intellect Analyst), a legal document analysis tool. It reviewed "
        "{agency_phrase} and found potential legal issues that may affect "
        "your rights. Legal terms are explained in plain English where possible."
    ),
    "council": (
        "This briefing was prepared by ODIA legal analysis for the attention "
        "of elected officials and their staff. It summarizes {agency_phrase} "
        "and flags areas that may require council action or agency response."
    ),
    "media": (
        "ODIA legal analysis reviewed {agency_phrase} and identified the "
        "following potential legal issues. Key findings are summarized below "
        "for public reporting purposes."
    ),
}

_CLOSINGS: dict[str, str] = {
    "community": (
        "What can you do?\n\n"
        "  • Attend the next city council or oversight committee meeting and "
        "raise these issues during public comment.\n"
        "  • File a public records request (it's free and easy — visit "
        "muckrock.com for help).\n"
        "  • Contact a local civil liberties organization if you believe your "
        "rights have been violated."
    ),
    "council": (
        "Recommended next steps:\n\n"
        "  • Request a written response from the agency addressing each "
        "high-severity finding.\n"
        "  • Schedule an agenda item for the next meeting to review compliance.\n"
        "  • Direct agency counsel to assess litigation exposure."
    ),
    "media": (
        "Questions for the agency:\n\n"
        "  • Has the agency reviewed these findings?\n"
        "  • What corrective actions, if any, are planned?\n"
        "  • When was the last independent legal review of these policies?"
    ),
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _plain(text: str) -> str:
    """Apply jargon substitutions to make text more accessible."""
    for term, replacement in _JARGON.items():
        if term in text and replacement not in text:
            text = text.replace(term, replacement, 1)
    return text


def _wrap(text: str) -> str:
    return textwrap.fill(text, width=_LINE_WIDTH)


def _fmt_finding_plain(finding: dict[str, Any], index: int) -> str:
    """Render a single finding in plain language."""
    severity = finding.get("severity", "low")
    issue = finding.get("issue", "")
    details = finding.get("details", {})
    layer = finding.get("layer", "")

    label = _SEVERITY_PLAIN.get(severity, "NOTE")
    action = _SEVERITY_ACTION.get(severity, "")
    detail_text = details.get("detail") or details.get("relevance") or ""

    lines: list[str] = [
        f"  {index}. [{label}]",
        f"     {_wrap(_plain(issue))}",
    ]
    if detail_text:
        lines.append(f"     What this means: {_wrap(_plain(detail_text))}")
    if action:
        lines.append(f"     {action}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Explainer dataclass
# ---------------------------------------------------------------------------


@dataclass
class Explainer:
    """A plain-language community education explainer."""

    title_line: str
    intro: str
    summary_table: str
    sections: list[tuple[str, str]]
    closing: str

    def to_text(self) -> str:
        lines: list[str] = [
            self.title_line,
            "=" * len(self.title_line),
            "",
            self.intro,
            "",
            self.summary_table,
            "",
        ]
        for section_title, body in self.sections:
            lines += [
                f"── {section_title} ──",
                "",
                body,
                "",
            ]
        lines += [
            "── What You Can Do ──",
            "",
            self.closing,
            "",
        ]
        return "\n".join(lines)

    def to_html(self) -> str:
        parts: list[str] = [
            f"<h1>{self.title_line}</h1>",
            f"<p>{self.intro}</p>",
            "<h2>Summary</h2>",
            f"<pre>{self.summary_table}</pre>",
        ]
        for section_title, body in self.sections:
            body_html = body.replace("\n\n", "</p><p>").replace("\n", "<br>")
            parts.append(f"<h2>{section_title}</h2><p>{body_html}</p>")
        closing_html = self.closing.replace("\n", "<br>")
        parts.append(f"<h2>What You Can Do</h2><p>{closing_html}</p>")
        return "\n".join(parts)

    def __str__(self) -> str:
        return self.to_text()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_explainer(
    doc_meta: dict[str, Any],
    findings: list[dict[str, Any]],
    *,
    audience: Audience = "community",
) -> Explainer:
    """Generate a plain-language explainer for community education.

    Args:
        doc_meta:  Document metadata. Recognized keys: 'title', 'agency', 'date'.
        findings:  List of standard ODIA finding dicts.
        audience:  Target audience — 'community', 'council', or 'media'.

    Returns:
        Explainer dataclass with .to_text() and .to_html() methods.
    """
    title = doc_meta.get("title") or "Untitled Document"
    agency = doc_meta.get("agency", "the agency")
    doc_date = doc_meta.get("date", "")

    agency_phrase = f'a document from "{agency}"'
    if doc_date:
        agency_phrase += f" dated {doc_date}"

    title_line = f"Plain-Language Summary: {title}"
    intro = _wrap(_INTROS[audience].format(agency_phrase=agency_phrase))

    # Summary table
    total = len(findings)
    high = sum(1 for f in findings if f.get("severity") == "high")
    medium = sum(1 for f in findings if f.get("severity") == "medium")
    low = sum(1 for f in findings if f.get("severity") == "low")

    summary_lines = [
        "FINDINGS AT A GLANCE",
        f"  Total issues found : {total}",
        f"  Serious concerns   : {high}",
        f"  Worth investigating: {medium}",
        f"  Informational      : {low}",
    ]
    summary_table = "\n".join(summary_lines)

    # Group by layer → plain section title
    layer_findings: dict[str, list[dict[str, Any]]] = {}
    for f in findings:
        layer = f.get("layer", "other")
        layer_findings.setdefault(layer, []).append(f)

    sections: list[tuple[str, str]] = []
    for layer, layer_items in layer_findings.items():
        section_title = _LAYER_LABELS.get(layer, layer.replace("_", " ").title())
        body_parts: list[str] = []
        for i, finding in enumerate(layer_items, 1):
            body_parts.append(_fmt_finding_plain(finding, i))
        sections.append((section_title, "\n\n".join(body_parts)))

    closing = _CLOSINGS[audience]

    return Explainer(
        title_line=title_line,
        intro=intro,
        summary_table=summary_table,
        sections=sections,
        closing=closing,
    )
