"use strict";

const { app, BrowserWindow, ipcMain, dialog, shell } = require("electron");
const path = require("path");
const { fileURLToPath } = require("url");
const log = require("electron-log");

const { startBackend, stopBackend, waitForBackend } = require("./backend");
const { registerIpcHandlers } = require("./ipc");

// Configure logging
log.transports.file.level = "info";
log.transports.console.level = "debug";

/** @type {BrowserWindow | null} */
let mainWindow = null;

/**
 * Resolve the path to the frontend static files.
 * In development, serves from the Next.js static export directory (frontend/out/).
 * Build with: ELECTRON_BUILD=1 npm run build (in frontend/).
 * In production, serves from the bundled resources.
 * @returns {string} Absolute path to frontend directory
 */
function getFrontendPath() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, "frontend");
  }
  // Development: use Next.js static export output (generated by ELECTRON_BUILD=1 next build)
  return path.join(__dirname, "..", "..", "frontend", "out");
}

/**
 * Create the main application window with security best practices.
 */
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    title: "ODIA — Document Analysis",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
    },
    show: false,
  });

  // Show window when ready to avoid visual flash
  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });

  // Open external links in the default browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith("https://") || url.startsWith("http://")) {
      shell.openExternal(url);
    }
    return { action: "deny" };
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });

  // Load frontend
  const frontendPath = getFrontendPath();
  const indexPath = path.join(frontendPath, "index.html");
  log.info(`Loading frontend from: ${indexPath}`);
  mainWindow.loadFile(indexPath).catch((err) => {
    log.error("Failed to load frontend:", err);
    // Show error page if frontend fails to load
    mainWindow.loadURL(
      `data:text/html,<html><body style="font-family:sans-serif;padding:40px;">
        <h1>ODIA</h1>
        <p>Frontend failed to load. Please check the installation.</p>
        <pre>${err.message}</pre>
      </body></html>`
    );
  });
}

/**
 * Application startup sequence:
 *
 *   1. Register IPC handlers (cheap, synchronous)
 *   2. Create the main window immediately
 *   3. Kick off the Python backend in the background
 *   4. The renderer's sidebar pill (DashboardLayout.tsx) drives its own
 *      health polling against /api/v1/health and surfaces the connection
 *      state inline, so there is no need to block the window on backend
 *      readiness.
 *   5. Only show a blocking error dialog if the backend *process* exits
 *      unexpectedly (real crash), not on a slow cold-start.
 *
 * This matters on Windows: PyInstaller bootloader + bundled Python +
 * sklearn/pydantic/fastapi takes noticeably longer than 30 s on first
 * launch (antivirus scanning each extracted file), and the previous
 * flow showed an alarming "Backend Startup Error" dialog in what was
 * actually a perfectly normal cold start.
 */
async function onReady() {
  log.info("ODIA Desktop starting...");
  log.info(`App version: ${app.getVersion()}`);
  log.info(`Electron: ${process.versions.electron}`);
  log.info(`Platform: ${process.platform} ${process.arch}`);

  // 1. Register IPC handlers up front so they're ready the moment the
  //    renderer starts making requests.
  registerIpcHandlers(ipcMain, dialog);

  // 2. Open the window immediately — don't make the user stare at a
  //    blank screen while PyInstaller unpacks.
  createWindow();

  // 3. Start the backend in the background.
  try {
    log.info("Starting Python backend (background)...");
    startBackend();
  } catch (err) {
    log.error("Backend failed to spawn:", err);
    // Spawn failure is the one case we surface immediately — the
    // sidebar pill can't recover from a process that never started.
    dialog.showErrorBox(
      "Backend failed to start",
      "The analysis backend could not be launched.\n\n" +
        (err && err.message ? err.message : String(err)) +
        "\n\nPlease reinstall O.D.I.A. or check the application logs.",
    );
    return;
  }

  // 4. Wait for the backend, but don't block on it.  Log timing for
  //    diagnostics; the sidebar pill is the user-facing status.
  const startedAt = Date.now();
  waitForBackend(120_000)
    .then((ready) => {
      if (ready) {
        log.info(`Backend ready after ${Date.now() - startedAt} ms`);
      } else {
        log.error(
          `Backend did not respond within 120 s (sidebar will still show offline)`,
        );
      }
    })
    .catch((err) => {
      log.error("Backend readiness check failed:", err);
    });
}

// App lifecycle
app.whenReady().then(onReady);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (mainWindow === null) {
    createWindow();
  }
});

app.on("before-quit", () => {
  log.info("Shutting down backend...");
  stopBackend();
});

// Security: Prevent navigation outside the bundled frontend directory.
// Uses fileURLToPath for reliable cross-platform path comparison.
// On Windows (case-insensitive filesystem) paths are normalized to lowercase.
app.on("web-contents-created", (_event, contents) => {
  contents.on("will-navigate", (event, url) => {
    try {
      const rawNavigated = path.resolve(fileURLToPath(new URL(url)));
      const rawFrontend = path.resolve(getFrontendPath());

      // Normalize for case-insensitive filesystems (Windows NTFS)
      const normalize = (p) =>
        process.platform === "win32" ? p.toLowerCase() : p;

      const navigatedPath = normalize(rawNavigated);
      const frontendDir = normalize(rawFrontend);

      if (
        !navigatedPath.startsWith(frontendDir + path.sep) &&
        navigatedPath !== frontendDir
      ) {
        event.preventDefault();
        log.warn(`Blocked navigation to: ${url}`);
      }
    } catch {
      // Not a file:// URL (or URL parsing failed) — block it
      event.preventDefault();
      log.warn(`Blocked non-file navigation to: ${url}`);
    }
  });
});

module.exports = { createWindow, getFrontendPath };
