"use strict";

const { app, BrowserWindow, ipcMain, dialog, shell } = require("electron");
const path = require("path");
const { fileURLToPath } = require("url");
const log = require("electron-log");

const { startBackend, stopBackend, waitForBackend } = require("./backend");
const { registerIpcHandlers } = require("./ipc");

// Configure logging
log.transports.file.level = "info";
log.transports.console.level = "debug";

/** @type {BrowserWindow | null} */
let mainWindow = null;

/**
 * Resolve the path to the frontend static files.
 * In development, serves from the Next.js static export directory (frontend/out/).
 * Build with: ELECTRON_BUILD=1 npm run build (in frontend/).
 * In production, serves from the bundled resources.
 * @returns {string} Absolute path to frontend directory
 */
function getFrontendPath() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, "frontend");
  }
  // Development: use Next.js static export output (generated by ELECTRON_BUILD=1 next build)
  return path.join(__dirname, "..", "..", "frontend", "out");
}

/**
 * Create the main application window with security best practices.
 */
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    title: "ODIA — Document Analysis",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
    },
    show: false,
  });

  // Show window when ready to avoid visual flash
  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });

  // Open external links in the default browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith("https://") || url.startsWith("http://")) {
      shell.openExternal(url);
    }
    return { action: "deny" };
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });

  // Load frontend
  const frontendPath = getFrontendPath();
  const indexPath = path.join(frontendPath, "index.html");
  log.info(`Loading frontend from: ${indexPath}`);
  mainWindow.loadFile(indexPath).catch((err) => {
    log.error("Failed to load frontend:", err);
    // Show error page if frontend fails to load
    mainWindow.loadURL(
      `data:text/html,<html><body style="font-family:sans-serif;padding:40px;">
        <h1>ODIA</h1>
        <p>Frontend failed to load. Please check the installation.</p>
        <pre>${err.message}</pre>
      </body></html>`
    );
  });
}

/**
 * Application startup sequence:
 * 1. Start Python backend
 * 2. Wait for backend health check
 * 3. Create main window
 * 4. Register IPC handlers
 */
async function onReady() {
  log.info("ODIA Desktop starting...");
  log.info(`App version: ${app.getVersion()}`);
  log.info(`Electron: ${process.versions.electron}`);
  log.info(`Platform: ${process.platform} ${process.arch}`);

  try {
    // Start backend
    log.info("Starting Python backend...");
    startBackend();

    // Wait for backend to be ready (60 second timeout — PyInstaller cold-start is slow)
    const backendReady = await waitForBackend(60000);
    if (!backendReady) {
      log.error("Backend failed to start within 60 seconds");
      dialog.showErrorBox(
        "Backend Startup Error",
        "The analysis backend failed to start within 60 seconds.\n\n" +
          "Please ensure ODIA is installed correctly and try again."
      );
    } else {
      log.info("Backend is ready");
    }
  } catch (err) {
    log.error("Backend startup error:", err);
  }

  // Register IPC handlers
  registerIpcHandlers(ipcMain, dialog);

  // Create the main window
  createWindow();
}

// App lifecycle
app.whenReady().then(onReady);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (mainWindow === null) {
    createWindow();
  }
});

app.on("before-quit", () => {
  log.info("Shutting down backend...");
  stopBackend();
});

// Security: Prevent navigation outside the bundled frontend directory.
// Uses fileURLToPath for reliable cross-platform path comparison.
// On Windows (case-insensitive filesystem) paths are normalized to lowercase.
app.on("web-contents-created", (_event, contents) => {
  contents.on("will-navigate", (event, url) => {
    try {
      const rawNavigated = path.resolve(fileURLToPath(new URL(url)));
      const rawFrontend = path.resolve(getFrontendPath());

      // Normalize for case-insensitive filesystems (Windows NTFS)
      const normalize = (p) =>
        process.platform === "win32" ? p.toLowerCase() : p;

      const navigatedPath = normalize(rawNavigated);
      const frontendDir = normalize(rawFrontend);

      if (
        !navigatedPath.startsWith(frontendDir + path.sep) &&
        navigatedPath !== frontendDir
      ) {
        event.preventDefault();
        log.warn(`Blocked navigation to: ${url}`);
      }
    } catch {
      // Not a file:// URL (or URL parsing failed) — block it
      event.preventDefault();
      log.warn(`Blocked non-file navigation to: ${url}`);
    }
  });
});

module.exports = { createWindow, getFrontendPath };
