#!/usr/bin/env python3
"""Generate timeline visualization for the Public Transparency Release.

This script creates a timeline_public.png showing:
- Document clusters by year
- Anomaly density by year
- Vendor presence timeline
- Key technology programs

Author: GitHub Copilot Agent
Date: 2025-12-06
"""

import sys
from collections import defaultdict
from pathlib import Path

# Add paths for imports
_script_dir = Path(__file__).parent
_repo_root = _script_dir.parent
sys.path.insert(0, str(_repo_root / "src"))
sys.path.insert(0, str(_repo_root))

from scripts.corpus_manager import HIST_FILES

try:
    import matplotlib.patches as mpatches
    import matplotlib.pyplot as plt

    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False

# Constants
TRANSPARENCY_DIR = _repo_root / "transparency_release"


def count_by_year() -> dict:
    """Count corpus records by year."""
    counts = defaultdict(int)
    for meeting_date in HIST_FILES.values():
        year = int(meeting_date[:4])
        counts[year] += 1
    return dict(sorted(counts.items()))


def get_vendor_timeline() -> dict:
    """Get vendor presence by year."""
    return {
        "Axon": [2015, 2017, 2018, 2019, 2020, 2022, 2023, 2024, 2025],
        "Flock Safety": [2024, 2025],
        "JAG Grants": [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2024],
    }


def generate_timeline_png(output_path: Path):
    """Generate timeline visualization."""
    if not HAS_MATPLOTLIB:
        print("matplotlib not available, skipping timeline generation")
        return False

    # Data
    year_counts = count_by_year()
    years = list(range(2014, 2026))
    counts = [year_counts.get(y, 0) for y in years]
    vendor_timeline = get_vendor_timeline()

    # Create figure with multiple subplots
    fig, axes = plt.subplots(
        2, 1, figsize=(14, 10), gridspec_kw={"height_ratios": [2, 1]}
    )
    fig.suptitle(
        "Oraculus-DI-Auditor: 2014-2025 Legislative Corpus Timeline",
        fontsize=16,
        fontweight="bold",
        y=0.98,
    )

    # Top plot: Document count by year
    ax1 = axes[0]
    colors = ["#3498db" if c > 0 else "#e74c3c" for c in counts]
    bars = ax1.bar(years, counts, color=colors, edgecolor="navy", linewidth=1.2)

    # Add value labels on bars
    for bar, count in zip(bars, counts, strict=False):
        if count > 0:
            ax1.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.1,
                str(count),
                ha="center",
                va="bottom",
                fontsize=10,
                fontweight="bold",
            )

    ax1.set_xlabel("Year", fontsize=12)
    ax1.set_ylabel("Number of Records", fontsize=12)
    ax1.set_title("Document Records by Year", fontsize=14, pad=10)
    ax1.set_xticks(years)
    ax1.set_xticklabels([str(y) for y in years], rotation=45, ha="right")
    ax1.set_ylim(0, max(counts) + 2)
    ax1.grid(axis="y", alpha=0.3)
    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)

    # Bottom plot: Vendor/Program timeline
    ax2 = axes[1]
    vendor_colors = {
        "Axon": "#e74c3c",
        "Flock Safety": "#2ecc71",
        "JAG Grants": "#9b59b6",
    }

    y_positions = {vendor: i for i, vendor in enumerate(vendor_timeline.keys())}

    for vendor, vendor_years in vendor_timeline.items():
        y = y_positions[vendor]
        for year in vendor_years:
            if year in years:
                x_idx = years.index(year)
                ax2.scatter(
                    year,
                    y,
                    s=200,
                    c=vendor_colors[vendor],
                    marker="s",
                    edgecolors="black",
                    linewidths=1,
                )

    ax2.set_xlabel("Year", fontsize=12)
    ax2.set_ylabel("", fontsize=12)
    ax2.set_title("Vendor/Program Presence by Year", fontsize=14, pad=10)
    ax2.set_xticks(years)
    ax2.set_xticklabels([str(y) for y in years], rotation=45, ha="right")
    ax2.set_yticks(list(y_positions.values()))
    ax2.set_yticklabels(list(y_positions.keys()))
    ax2.set_ylim(-0.5, len(y_positions) - 0.5)
    ax2.grid(axis="x", alpha=0.3)
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)

    # Legend
    legend_patches = [
        mpatches.Patch(color=c, label=v) for v, c in vendor_colors.items()
    ]
    ax2.legend(handles=legend_patches, loc="upper right", fontsize=9)

    # Add footer text
    fig.text(
        0.5,
        0.02,
        "Generated by Oraculus-DI-Auditor | Public Transparency Release v1 | December 2025",
        ha="center",
        fontsize=9,
        style="italic",
        alpha=0.7,
    )

    # Adjust layout
    plt.tight_layout(rect=[0, 0.03, 1, 0.96])

    # Save
    plt.savefig(
        output_path, dpi=150, bbox_inches="tight", facecolor="white", edgecolor="none"
    )
    plt.close()

    print(f"  Generated: {output_path.relative_to(_repo_root)}")
    return True


def main():
    """Generate timeline visualization."""
    print("Generating timeline visualization...")

    output_path = TRANSPARENCY_DIR / "timeline_public.png"

    if generate_timeline_png(output_path):
        print("Timeline generation complete!")
    else:
        print("Timeline generation skipped (matplotlib not available)")


if __name__ == "__main__":
    main()
